"""The starter universe: ~100 real, mostly-interconnected companies and the
real-world relationships between them (supplier / customer / competitor /
partner). This is the graph the whole product is built around.

Edge types:
    supplier   A supplies B (A -> B means "A supplies to B")
    customer   A is a major customer/buyer of B's output (inverse of supplier,
               kept separate so the direction of $ flow is explicit)
    competitor A and B compete directly for the same customers
    partner    A and B have a strategic partnership / alliance / joint venture

Weight (0-1) is a rough "how much this relationship matters to both
companies' stock price" judgment call, used to scale graph spillover.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Company:
    ticker: str
    name: str
    sector: str
    industry: str


@dataclass(frozen=True)
class Edge:
    src: str
    dst: str
    kind: str  # supplier | customer | competitor | partner
    weight: float = 0.5
    note: str = ""


COMPANIES: list[Company] = [
    # --- Big Tech / Platforms ---
    Company("AAPL", "Apple", "Technology", "Consumer Electronics"),
    Company("MSFT", "Microsoft", "Technology", "Software Infrastructure"),
    Company("GOOGL", "Alphabet", "Technology", "Internet Services"),
    Company("AMZN", "Amazon", "Consumer Discretionary", "E-Commerce/Cloud"),
    Company("META", "Meta Platforms", "Technology", "Internet Services"),
    Company("ORCL", "Oracle", "Technology", "Enterprise Software"),
    Company("CRM", "Salesforce", "Technology", "Enterprise Software"),
    Company("ADBE", "Adobe", "Technology", "Application Software"),
    Company("IBM", "IBM", "Technology", "IT Services"),
    Company("CSCO", "Cisco Systems", "Technology", "Networking Hardware"),
    Company("NOW", "ServiceNow", "Technology", "Enterprise Software"),
    Company("SNOW", "Snowflake", "Technology", "Data Cloud"),
    Company("PLTR", "Palantir", "Technology", "Data Analytics"),
    Company("SHOP", "Shopify", "Technology", "E-Commerce Software"),
    Company("UBER", "Uber", "Technology", "Mobility Platform"),
    Company("ABNB", "Airbnb", "Consumer Discretionary", "Travel Platform"),
    Company("NFLX", "Netflix", "Communication Services", "Streaming"),
    Company("DIS", "Disney", "Communication Services", "Media & Entertainment"),

    # --- Semiconductors & AI infrastructure ---
    Company("NVDA", "Nvidia", "Technology", "Semiconductors"),
    Company("AMD", "Advanced Micro Devices", "Technology", "Semiconductors"),
    Company("INTC", "Intel", "Technology", "Semiconductors"),
    Company("TSM", "Taiwan Semiconductor", "Technology", "Semiconductor Foundry"),
    Company("ASML", "ASML Holding", "Technology", "Semiconductor Equipment"),
    Company("AMAT", "Applied Materials", "Technology", "Semiconductor Equipment"),
    Company("LRCX", "Lam Research", "Technology", "Semiconductor Equipment"),
    Company("KLAC", "KLA Corp", "Technology", "Semiconductor Equipment"),
    Company("QCOM", "Qualcomm", "Technology", "Semiconductors"),
    Company("AVGO", "Broadcom", "Technology", "Semiconductors"),
    Company("TXN", "Texas Instruments", "Technology", "Semiconductors"),
    Company("MU", "Micron Technology", "Technology", "Memory Chips"),
    Company("ARM", "Arm Holdings", "Technology", "Chip IP Licensing"),
    Company("MRVL", "Marvell Technology", "Technology", "Semiconductors"),
    Company("ON", "ON Semiconductor", "Technology", "Semiconductors"),
    Company("ADI", "Analog Devices", "Technology", "Semiconductors"),
    Company("SMCI", "Super Micro Computer", "Technology", "Server Hardware"),
    Company("DELL", "Dell Technologies", "Technology", "Hardware"),
    Company("HPQ", "HP Inc", "Technology", "Hardware"),
    Company("HPE", "Hewlett Packard Enterprise", "Technology", "Enterprise Hardware"),

    # --- EV / Auto ---
    Company("TSLA", "Tesla", "Consumer Discretionary", "Electric Vehicles"),
    Company("GM", "General Motors", "Consumer Discretionary", "Automobiles"),
    Company("F", "Ford Motor", "Consumer Discretionary", "Automobiles"),
    Company("RIVN", "Rivian", "Consumer Discretionary", "Electric Vehicles"),
    Company("LCID", "Lucid Group", "Consumer Discretionary", "Electric Vehicles"),
    Company("TM", "Toyota Motor", "Consumer Discretionary", "Automobiles"),
    Company("STLA", "Stellantis", "Consumer Discretionary", "Automobiles"),
    Company("ALB", "Albemarle", "Materials", "Lithium/Battery Materials"),

    # --- Retail / Consumer ---
    Company("WMT", "Walmart", "Consumer Staples", "Retail"),
    Company("TGT", "Target", "Consumer Discretionary", "Retail"),
    Company("COST", "Costco", "Consumer Staples", "Retail"),
    Company("HD", "Home Depot", "Consumer Discretionary", "Home Improvement Retail"),
    Company("LOW", "Lowe's", "Consumer Discretionary", "Home Improvement Retail"),
    Company("NKE", "Nike", "Consumer Discretionary", "Apparel"),
    Company("SBUX", "Starbucks", "Consumer Discretionary", "Restaurants"),
    Company("MCD", "McDonald's", "Consumer Discretionary", "Restaurants"),
    Company("PG", "Procter & Gamble", "Consumer Staples", "Household Products"),
    Company("KO", "Coca-Cola", "Consumer Staples", "Beverages"),
    Company("PEP", "PepsiCo", "Consumer Staples", "Beverages"),
    Company("FDX", "FedEx", "Industrials", "Logistics"),
    Company("UPS", "United Parcel Service", "Industrials", "Logistics"),

    # --- Financials ---
    Company("JPM", "JPMorgan Chase", "Financials", "Banking"),
    Company("BAC", "Bank of America", "Financials", "Banking"),
    Company("GS", "Goldman Sachs", "Financials", "Investment Banking"),
    Company("MS", "Morgan Stanley", "Financials", "Investment Banking"),
    Company("C", "Citigroup", "Financials", "Banking"),
    Company("V", "Visa", "Financials", "Payments"),
    Company("MA", "Mastercard", "Financials", "Payments"),
    Company("PYPL", "PayPal", "Financials", "Payments"),
    Company("AXP", "American Express", "Financials", "Payments/Credit"),

    # --- Energy ---
    Company("XOM", "Exxon Mobil", "Energy", "Oil & Gas"),
    Company("CVX", "Chevron", "Energy", "Oil & Gas"),
    Company("COP", "ConocoPhillips", "Energy", "Oil & Gas E&P"),
    Company("SLB", "Schlumberger", "Energy", "Oilfield Services"),

    # --- Airlines ---
    Company("DAL", "Delta Air Lines", "Industrials", "Airlines"),
    Company("UAL", "United Airlines", "Industrials", "Airlines"),
    Company("AAL", "American Airlines", "Industrials", "Airlines"),
    Company("LUV", "Southwest Airlines", "Industrials", "Airlines"),
    Company("BA", "Boeing", "Industrials", "Aerospace"),

    # --- Telecom / Media ---
    Company("T", "AT&T", "Communication Services", "Telecom"),
    Company("VZ", "Verizon", "Communication Services", "Telecom"),
    Company("TMUS", "T-Mobile US", "Communication Services", "Telecom"),
    Company("CMCSA", "Comcast", "Communication Services", "Media/Telecom"),

    # --- Healthcare / Pharma ---
    Company("UNH", "UnitedHealth Group", "Healthcare", "Health Insurance"),
    Company("CVS", "CVS Health", "Healthcare", "Pharmacy/Insurance"),
    Company("JNJ", "Johnson & Johnson", "Healthcare", "Pharmaceuticals"),
    Company("PFE", "Pfizer", "Healthcare", "Pharmaceuticals"),
    Company("MRK", "Merck & Co", "Healthcare", "Pharmaceuticals"),
    Company("LLY", "Eli Lilly", "Healthcare", "Pharmaceuticals"),
    Company("ABBV", "AbbVie", "Healthcare", "Pharmaceuticals"),

    # --- Industrials ---
    Company("CAT", "Caterpillar", "Industrials", "Machinery"),
    Company("GE", "GE Aerospace", "Industrials", "Aerospace"),
    Company("HON", "Honeywell", "Industrials", "Diversified Industrials"),
    Company("UNP", "Union Pacific", "Industrials", "Rail"),

    # --- Software / AI adjacent ---
    Company("PANW", "Palo Alto Networks", "Technology", "Cybersecurity"),
    Company("CRWD", "CrowdStrike", "Technology", "Cybersecurity"),
    Company("NET", "Cloudflare", "Technology", "Cloud/Edge Infrastructure"),
    Company("DDOG", "Datadog", "Technology", "Cloud Monitoring"),
    Company("FTNT", "Fortinet", "Technology", "Cybersecurity"),
    Company("ZS", "Zscaler", "Technology", "Cybersecurity"),
    Company("OKTA", "Okta", "Technology", "Identity Management"),
    Company("MDB", "MongoDB", "Technology", "Database Software"),
    Company("INTU", "Intuit", "Technology", "Financial Software"),
    Company("ADSK", "Autodesk", "Technology", "Design Software"),
    Company("WDAY", "Workday", "Technology", "Enterprise Software"),
    Company("TEAM", "Atlassian", "Technology", "Collaboration Software"),
    Company("DOCU", "DocuSign", "Technology", "E-Signature Software"),
    Company("TTD", "The Trade Desk", "Technology", "Ad Tech"),
    Company("CDNS", "Cadence Design Systems", "Technology", "Chip Design Software"),
    Company("SNPS", "Synopsys", "Technology", "Chip Design Software"),
    Company("TER", "Teradyne", "Technology", "Semiconductor Test Equipment"),
    Company("SWKS", "Skyworks Solutions", "Technology", "RF Semiconductors"),
    Company("QRVO", "Qorvo", "Technology", "RF Semiconductors"),

    # --- Consumer internet / entertainment ---
    Company("SPOT", "Spotify", "Communication Services", "Audio Streaming"),
    Company("EA", "Electronic Arts", "Communication Services", "Video Games"),
    Company("TTWO", "Take-Two Interactive", "Communication Services", "Video Games"),
    Company("RBLX", "Roblox", "Communication Services", "Gaming Platform"),
    Company("PINS", "Pinterest", "Communication Services", "Social Media"),
    Company("SNAP", "Snap Inc", "Communication Services", "Social Media"),
    Company("MTCH", "Match Group", "Communication Services", "Online Dating"),
    Company("EBAY", "eBay", "Consumer Discretionary", "E-Commerce"),
    Company("ETSY", "Etsy", "Consumer Discretionary", "E-Commerce"),
    Company("BKNG", "Booking Holdings", "Consumer Discretionary", "Travel Platform"),
    Company("MAR", "Marriott International", "Consumer Discretionary", "Hotels"),
    Company("HLT", "Hilton Worldwide", "Consumer Discretionary", "Hotels"),
    Company("EXPE", "Expedia Group", "Consumer Discretionary", "Travel Platform"),
    Company("LYV", "Live Nation Entertainment", "Communication Services", "Live Events"),
    Company("CCL", "Carnival Corp", "Consumer Discretionary", "Cruise Lines"),
    Company("RCL", "Royal Caribbean", "Consumer Discretionary", "Cruise Lines"),
    Company("WBD", "Warner Bros Discovery", "Communication Services", "Media & Entertainment"),
    Company("PARA", "Paramount Global", "Communication Services", "Media & Entertainment"),

    # --- Retail / Apparel ---
    Company("LULU", "Lululemon Athletica", "Consumer Discretionary", "Apparel"),
    Company("TJX", "TJX Companies", "Consumer Discretionary", "Off-Price Retail"),
    Company("ROST", "Ross Stores", "Consumer Discretionary", "Off-Price Retail"),

    # --- Healthcare / Pharma / Biotech ---
    Company("BMY", "Bristol Myers Squibb", "Healthcare", "Pharmaceuticals"),
    Company("GILD", "Gilead Sciences", "Healthcare", "Biotechnology"),
    Company("AMGN", "Amgen", "Healthcare", "Biotechnology"),
    Company("REGN", "Regeneron Pharmaceuticals", "Healthcare", "Biotechnology"),
    Company("VRTX", "Vertex Pharmaceuticals", "Healthcare", "Biotechnology"),
    Company("MDT", "Medtronic", "Healthcare", "Medical Devices"),
    Company("ISRG", "Intuitive Surgical", "Healthcare", "Medical Devices"),
    Company("SYK", "Stryker", "Healthcare", "Medical Devices"),
    Company("DHR", "Danaher", "Healthcare", "Life Sciences Tools"),
    Company("TMO", "Thermo Fisher Scientific", "Healthcare", "Life Sciences Tools"),
    Company("CI", "Cigna", "Healthcare", "Health Insurance"),
    Company("ELV", "Elevance Health", "Healthcare", "Health Insurance"),
    Company("HUM", "Humana", "Healthcare", "Health Insurance"),

    # --- Financials (asset managers, exchanges, big banks) ---
    Company("SCHW", "Charles Schwab", "Financials", "Brokerage"),
    Company("BLK", "BlackRock", "Financials", "Asset Management"),
    Company("BX", "Blackstone", "Financials", "Private Equity"),
    Company("SPGI", "S&P Global", "Financials", "Financial Data/Ratings"),
    Company("ICE", "Intercontinental Exchange", "Financials", "Exchanges"),
    Company("CME", "CME Group", "Financials", "Exchanges"),
    Company("COF", "Capital One", "Financials", "Banking/Credit Cards"),
    Company("USB", "US Bancorp", "Financials", "Banking"),
    Company("WFC", "Wells Fargo", "Financials", "Banking"),
    Company("PNC", "PNC Financial Services", "Financials", "Banking"),

    # --- Energy (refiners, E&P, oilfield services) ---
    Company("OXY", "Occidental Petroleum", "Energy", "Oil & Gas E&P"),
    Company("PSX", "Phillips 66", "Energy", "Refining"),
    Company("MPC", "Marathon Petroleum", "Energy", "Refining"),
    Company("VLO", "Valero Energy", "Energy", "Refining"),
    Company("EOG", "EOG Resources", "Energy", "Oil & Gas E&P"),
    Company("DVN", "Devon Energy", "Energy", "Oil & Gas E&P"),
    Company("HAL", "Halliburton", "Energy", "Oilfield Services"),
    Company("BKR", "Baker Hughes", "Energy", "Oilfield Services"),

    # --- Materials ---
    Company("LIN", "Linde plc", "Materials", "Industrial Gases"),
    Company("SHW", "Sherwin-Williams", "Materials", "Paints & Coatings"),
    Company("NEM", "Newmont Corp", "Materials", "Gold Mining"),
    Company("FCX", "Freeport-McMoRan", "Materials", "Copper Mining"),
    Company("DOW", "Dow Inc", "Materials", "Chemicals"),
    Company("DD", "DuPont de Nemours", "Materials", "Chemicals"),

    # --- Consumer Staples ---
    Company("MDLZ", "Mondelez International", "Consumer Staples", "Packaged Foods"),
    Company("CL", "Colgate-Palmolive", "Consumer Staples", "Household Products"),
    Company("KMB", "Kimberly-Clark", "Consumer Staples", "Household Products"),
    Company("GIS", "General Mills", "Consumer Staples", "Packaged Foods"),
    Company("KHC", "Kraft Heinz", "Consumer Staples", "Packaged Foods"),
    Company("MNST", "Monster Beverage", "Consumer Staples", "Beverages"),
    Company("CLX", "Clorox", "Consumer Staples", "Household Products"),

    # --- Utilities / REITs ---
    Company("NEE", "NextEra Energy", "Utilities", "Electric Utilities"),
    Company("DUK", "Duke Energy", "Utilities", "Electric Utilities"),
    Company("SO", "Southern Company", "Utilities", "Electric Utilities"),
    Company("AEP", "American Electric Power", "Utilities", "Electric Utilities"),
    Company("PLD", "Prologis", "Real Estate", "Industrial REIT"),
    Company("AMT", "American Tower", "Real Estate", "Cell Tower REIT"),
    Company("EQIX", "Equinix", "Real Estate", "Data Center REIT"),
    Company("DLR", "Digital Realty Trust", "Real Estate", "Data Center REIT"),

    # --- Industrials (defense, machinery, diversified) ---
    Company("LMT", "Lockheed Martin", "Industrials", "Aerospace & Defense"),
    Company("RTX", "RTX Corp", "Industrials", "Aerospace & Defense"),
    Company("NOC", "Northrop Grumman", "Industrials", "Aerospace & Defense"),
    Company("GD", "General Dynamics", "Industrials", "Aerospace & Defense"),
    Company("DE", "Deere & Company", "Industrials", "Machinery"),
    Company("MMM", "3M Company", "Industrials", "Diversified Industrials"),
    Company("ITW", "Illinois Tool Works", "Industrials", "Diversified Industrials"),
    Company("EMR", "Emerson Electric", "Industrials", "Industrial Automation"),
    Company("APTV", "Aptiv", "Consumer Discretionary", "Auto Parts/Tech"),
    Company("BWA", "BorgWarner", "Consumer Discretionary", "Auto Parts"),

    # --- Insurance ---
    Company("AIG", "American International Group", "Financials", "Insurance (Multiline)"),
    Company("TRV", "Travelers Companies", "Financials", "Insurance (P&C)"),
    Company("PGR", "Progressive", "Financials", "Insurance (Auto)"),
    Company("ALL", "Allstate", "Financials", "Insurance (P&C)"),
    Company("MET", "MetLife", "Financials", "Insurance (Life)"),
    Company("PRU", "Prudential Financial", "Financials", "Insurance (Life)"),
    Company("AFL", "Aflac", "Financials", "Insurance (Supplemental)"),
    Company("HIG", "The Hartford", "Financials", "Insurance (P&C)"),

    # --- Homebuilders ---
    Company("DHI", "D.R. Horton", "Consumer Discretionary", "Homebuilding"),
    Company("LEN", "Lennar", "Consumer Discretionary", "Homebuilding"),
    Company("PHM", "PulteGroup", "Consumer Discretionary", "Homebuilding"),
    Company("NVR", "NVR Inc", "Consumer Discretionary", "Homebuilding"),

    # --- Rail / Trucking / Logistics ---
    Company("CSX", "CSX Corp", "Industrials", "Rail"),
    Company("NSC", "Norfolk Southern", "Industrials", "Rail"),
    Company("ODFL", "Old Dominion Freight Line", "Industrials", "Trucking"),

    # --- Metals & Mining ---
    Company("NUE", "Nucor", "Materials", "Steel"),
    Company("STLD", "Steel Dynamics", "Materials", "Steel"),
    Company("AA", "Alcoa", "Materials", "Aluminum"),

    # --- Restaurants ---
    Company("CMG", "Chipotle Mexican Grill", "Consumer Discretionary", "Restaurants"),
    Company("YUM", "Yum! Brands", "Consumer Discretionary", "Restaurants"),
    Company("DPZ", "Domino's Pizza", "Consumer Discretionary", "Restaurants"),

    # --- Crypto-adjacent ---
    Company("COIN", "Coinbase Global", "Financials", "Crypto Exchange"),
    Company("MSTR", "MicroStrategy", "Technology", "Bitcoin Treasury/Software"),

    # --- Agriculture ---
    Company("ADM", "Archer-Daniels-Midland", "Consumer Staples", "Agribusiness"),
    Company("BG", "Bunge Global", "Consumer Staples", "Agribusiness"),
    Company("CTVA", "Corteva", "Materials", "Agricultural Chemicals"),

    # --- Healthcare / Biotech (additional) ---
    Company("BIIB", "Biogen", "Healthcare", "Biotech"),
    Company("MRNA", "Moderna", "Healthcare", "Biotech"),
    Company("ZTS", "Zoetis", "Healthcare", "Animal Health"),

    # --- Regional Banks ---
    Company("TFC", "Truist Financial", "Financials", "Banking"),
    Company("FITB", "Fifth Third Bancorp", "Financials", "Banking"),

    # --- Media (additional) ---
    Company("FOXA", "Fox Corp", "Communication Services", "Media"),
    Company("NWSA", "News Corp", "Communication Services", "Media/Publishing"),

    # --- Apparel / Luxury (additional) ---
    Company("RL", "Ralph Lauren", "Consumer Discretionary", "Apparel/Luxury"),
    Company("TPR", "Tapestry", "Consumer Discretionary", "Apparel/Luxury"),

    # --- Packaging ---
    Company("IP", "International Paper", "Materials", "Packaging"),
    Company("PKG", "Packaging Corp of America", "Materials", "Packaging"),

    # --- Water Utility ---
    Company("AWK", "American Water Works", "Utilities", "Water"),

    # --- Real Estate / REITs (expansion) ---
    Company("O", "Realty Income", "Real Estate", "Retail REIT"),
    Company("SPG", "Simon Property Group", "Real Estate", "Retail REIT"),
    Company("WELL", "Welltower", "Real Estate", "Healthcare REIT"),
    Company("PSA", "Public Storage", "Real Estate", "Self-Storage REIT"),
    Company("AVB", "AvalonBay Communities", "Real Estate", "Residential REIT"),
    Company("EQR", "Equity Residential", "Real Estate", "Residential REIT"),
    Company("VTR", "Ventas", "Real Estate", "Healthcare REIT"),
    Company("EXR", "Extra Space Storage", "Real Estate", "Self-Storage REIT"),
    Company("IRM", "Iron Mountain", "Real Estate", "Specialty REIT"),
    Company("CCI", "Crown Castle", "Real Estate", "Communications REIT"),

    # --- Utilities (expansion) ---
    Company("D", "Dominion Energy", "Utilities", "Electric Utility"),
    Company("EXC", "Exelon", "Utilities", "Electric Utility"),
    Company("AEE", "Ameren", "Utilities", "Electric Utility"),
    Company("ED", "Consolidated Edison", "Utilities", "Electric Utility"),
    Company("XEL", "Xcel Energy", "Utilities", "Electric Utility"),
    Company("PEG", "Public Service Enterprise Group", "Utilities", "Electric Utility"),
    Company("WEC", "WEC Energy Group", "Utilities", "Electric Utility"),
    Company("SRE", "Sempra", "Utilities", "Multi-Utility"),

    # --- Financials (regional banks, insurance brokers, asset managers) ---
    Company("MTB", "M&T Bank", "Financials", "Regional Bank"),
    Company("RF", "Regions Financial", "Financials", "Regional Bank"),
    Company("CFG", "Citizens Financial Group", "Financials", "Regional Bank"),
    Company("KEY", "KeyCorp", "Financials", "Regional Bank"),
    Company("HBAN", "Huntington Bancshares", "Financials", "Regional Bank"),
    Company("ZION", "Zions Bancorporation", "Financials", "Regional Bank"),
    Company("CINF", "Cincinnati Financial", "Financials", "Insurance"),
    Company("AON", "Aon plc", "Financials", "Insurance Brokerage"),
    Company("MMC", "Marsh & McLennan", "Financials", "Insurance Brokerage"),
    Company("WTW", "Willis Towers Watson", "Financials", "Insurance Brokerage"),
    Company("TROW", "T. Rowe Price", "Financials", "Asset Management"),
    Company("BEN", "Franklin Resources", "Financials", "Asset Management"),
    Company("STT", "State Street", "Financials", "Custody Bank"),
    Company("BK", "BNY Mellon", "Financials", "Custody Bank"),
    Company("NDAQ", "Nasdaq Inc", "Financials", "Financial Exchange"),
    Company("CBOE", "Cboe Global Markets", "Financials", "Financial Exchange"),

    # --- Fintech / payments ---
    Company("SOFI", "SoFi Technologies", "Financials", "Fintech / Digital Banking"),
    Company("AFRM", "Affirm Holdings", "Financials", "Fintech / Buy-Now-Pay-Later"),
    Company("UPST", "Upstart Holdings", "Financials", "Fintech / AI Lending"),
    Company("FI", "Fiserv", "Financials", "Payments Processing"),
    Company("FIS", "Fidelity National Information Services", "Financials", "Payments Processing"),
    Company("GPN", "Global Payments", "Financials", "Payments Processing"),
    Company("XYZ", "Block", "Financials", "Payments / Fintech"),

    # --- Healthcare (expansion) ---
    Company("ABT", "Abbott Laboratories", "Healthcare", "Medical Devices/Diagnostics"),
    Company("BSX", "Boston Scientific", "Healthcare", "Medical Devices"),
    Company("EW", "Edwards Lifesciences", "Healthcare", "Medical Devices"),
    Company("IDXX", "IDEXX Laboratories", "Healthcare", "Diagnostics (Animal Health)"),
    Company("ZBH", "Zimmer Biomet", "Healthcare", "Medical Devices"),
    Company("HCA", "HCA Healthcare", "Healthcare", "Hospitals"),
    Company("DXCM", "Dexcom", "Healthcare", "Medical Devices"),
    Company("ALGN", "Align Technology", "Healthcare", "Medical Devices"),
    Company("VTRS", "Viatris", "Healthcare", "Generic Pharmaceuticals"),
    Company("CNC", "Centene", "Healthcare", "Managed Care"),
    Company("MOH", "Molina Healthcare", "Healthcare", "Managed Care"),
    Company("INCY", "Incyte", "Healthcare", "Biotechnology"),
    Company("EXAS", "Exact Sciences", "Healthcare", "Diagnostics"),

    # --- Consumer Staples (expansion) ---
    Company("DG", "Dollar General", "Consumer Staples", "Discount Retail"),
    Company("DLTR", "Dollar Tree", "Consumer Staples", "Discount Retail"),
    Company("KR", "Kroger", "Consumer Staples", "Grocery Retail"),
    Company("SYY", "Sysco", "Consumer Staples", "Food Distribution"),
    Company("HSY", "Hershey", "Consumer Staples", "Packaged Foods"),
    Company("KDP", "Keurig Dr Pepper", "Consumer Staples", "Beverages"),
    Company("STZ", "Constellation Brands", "Consumer Staples", "Beverages/Alcohol"),
    Company("TAP", "Molson Coors Beverage", "Consumer Staples", "Beverages/Alcohol"),
    Company("CHD", "Church & Dwight", "Consumer Staples", "Household Products"),
    Company("EL", "Estee Lauder", "Consumer Staples", "Personal Care"),
    Company("CAG", "Conagra Brands", "Consumer Staples", "Packaged Foods"),
    Company("K", "Kellanova", "Consumer Staples", "Packaged Foods"),
    Company("TSN", "Tyson Foods", "Consumer Staples", "Meat Processing"),
    Company("HRL", "Hormel Foods", "Consumer Staples", "Packaged Foods"),

    # --- Industrials (expansion) ---
    Company("PCAR", "Paccar", "Industrials", "Heavy Trucks"),
    Company("CMI", "Cummins", "Industrials", "Engines/Powertrain"),
    Company("PH", "Parker Hannifin", "Industrials", "Industrial Machinery"),
    Company("ETN", "Eaton", "Industrials", "Electrical Equipment"),
    Company("ROK", "Rockwell Automation", "Industrials", "Industrial Automation"),
    Company("DOV", "Dover Corp", "Industrials", "Industrial Machinery"),
    Company("IR", "Ingersoll Rand", "Industrials", "Industrial Machinery"),
    Company("XYL", "Xylem", "Industrials", "Water Technology"),
    Company("AME", "Ametek", "Industrials", "Electronic Instruments"),
    Company("FAST", "Fastenal", "Industrials", "Industrial Distribution"),
    Company("GWW", "W.W. Grainger", "Industrials", "Industrial Distribution"),
    Company("WM", "Waste Management", "Industrials", "Environmental Services"),
    Company("RSG", "Republic Services", "Industrials", "Environmental Services"),
    Company("CTAS", "Cintas", "Industrials", "Business Services"),
    Company("PAYX", "Paychex", "Industrials", "Payroll/HR Services"),
    Company("ADP", "Automatic Data Processing", "Industrials", "Payroll/HR Services"),
    Company("LHX", "L3Harris Technologies", "Industrials", "Aerospace & Defense"),
    Company("TDG", "TransDigm Group", "Industrials", "Aerospace Components"),
    Company("HII", "Huntington Ingalls Industries", "Industrials", "Shipbuilding/Defense"),
    Company("LDOS", "Leidos", "Industrials", "Defense/IT Services"),
    Company("AXON", "Axon Enterprise", "Industrials", "Public Safety Technology"),

    # --- Technology (expansion: semis, networking, cybersecurity, clean energy tech) ---
    Company("NXPI", "NXP Semiconductors", "Technology", "Semiconductors"),
    Company("MCHP", "Microchip Technology", "Technology", "Semiconductors"),
    Company("MPWR", "Monolithic Power Systems", "Technology", "Semiconductors"),
    Company("GFS", "GlobalFoundries", "Technology", "Semiconductor Foundry"),
    Company("ANET", "Arista Networks", "Technology", "Networking Hardware"),
    Company("JNPR", "Juniper Networks", "Technology", "Networking Hardware"),
    Company("FFIV", "F5 Inc", "Technology", "Networking/Security"),
    Company("AKAM", "Akamai Technologies", "Technology", "Cloud/CDN"),
    Company("GEN", "Gen Digital", "Technology", "Cybersecurity (Consumer)"),
    Company("CHKP", "Check Point Software", "Technology", "Cybersecurity"),
    Company("S", "SentinelOne", "Technology", "Cybersecurity"),
    Company("CYBR", "CyberArk Software", "Technology", "Cybersecurity"),
    Company("ENPH", "Enphase Energy", "Technology", "Solar Energy Equipment"),
    Company("SEDG", "SolarEdge Technologies", "Technology", "Solar Energy Equipment"),
    Company("ROKU", "Roku", "Technology", "Streaming Devices/Platform"),

    # --- Energy (expansion) ---
    Company("FSLR", "First Solar", "Energy", "Solar Equipment"),
    Company("PLUG", "Plug Power", "Energy", "Hydrogen Fuel Cells"),

    # --- Materials (expansion) ---
    Company("MOS", "Mosaic Company", "Materials", "Fertilizer"),
    Company("CF", "CF Industries", "Materials", "Nitrogen Fertilizer"),

    # --- Communication Services (expansion) ---
    Company("CHTR", "Charter Communications", "Communication Services", "Cable/Broadband"),
    Company("LUMN", "Lumen Technologies", "Communication Services", "Telecom Infrastructure"),
    Company("WMG", "Warner Music Group", "Communication Services", "Music/Entertainment"),

    # ---- Technology (expansion: software, storage, data-center infra) ----
    Company("CDW", "CDW Corp", "Technology", "IT Distribution"),
    Company("ANSS", "Ansys", "Technology", "Simulation Software"),
    Company("PTC", "PTC Inc", "Technology", "Industrial Software"),
    Company("VEEV", "Veeva Systems", "Technology", "Life Sciences Cloud Software"),
    Company("HUBS", "HubSpot", "Technology", "Marketing Software"),
    Company("ZM", "Zoom Communications", "Technology", "Video Conferencing"),
    Company("DBX", "Dropbox", "Technology", "Cloud Storage"),
    Company("BOX", "Box Inc", "Technology", "Cloud Content Management"),
    Company("PATH", "UiPath", "Technology", "Robotic Process Automation"),
    Company("U", "Unity Software", "Technology", "Game Engine Software"),
    Company("APP", "AppLovin", "Technology", "Mobile Ad Tech"),
    Company("ESTC", "Elastic", "Technology", "Search/Observability Software"),
    Company("NTNX", "Nutanix", "Technology", "Hybrid Cloud Infrastructure"),
    Company("WDC", "Western Digital", "Technology", "Data Storage"),
    Company("STX", "Seagate Technology", "Technology", "Data Storage"),
    Company("VRT", "Vertiv Holdings", "Technology", "Data Center Infrastructure"),
    Company("WOLF", "Wolfspeed", "Technology", "Silicon Carbide Semiconductors"),
    Company("LSCC", "Lattice Semiconductor", "Technology", "FPGA Semiconductors"),
    Company("CIEN", "Ciena Corp", "Technology", "Optical Networking"),
    Company("CACI", "CACI International", "Technology", "Government IT Services"),
    Company("GLW", "Corning", "Technology", "Specialty Glass & Fiber"),

    # ---- Consumer Discretionary (expansion: retail, footwear, restaurants) ----
    Company("YETI", "Yeti Holdings", "Consumer Discretionary", "Outdoor Products"),
    Company("CROX", "Crocs", "Consumer Discretionary", "Footwear"),
    Company("DECK", "Deckers Brands", "Consumer Discretionary", "Footwear"),
    Company("ULTA", "Ulta Beauty", "Consumer Discretionary", "Beauty Retail"),
    Company("BBY", "Best Buy", "Consumer Discretionary", "Electronics Retail"),
    Company("AZO", "AutoZone", "Consumer Discretionary", "Auto Parts Retail"),
    Company("ORLY", "O'Reilly Automotive", "Consumer Discretionary", "Auto Parts Retail"),
    Company("TSCO", "Tractor Supply", "Consumer Discretionary", "Rural Lifestyle Retail"),
    Company("DRI", "Darden Restaurants", "Consumer Discretionary", "Restaurants"),
    Company("WEN", "Wendy's", "Consumer Discretionary", "Restaurants"),
    Company("POOL", "Pool Corp", "Consumer Discretionary", "Pool Supplies Distribution"),
    Company("GRMN", "Garmin", "Consumer Discretionary", "Consumer Electronics/Wearables"),

    # ---- Communication Services (expansion: advertising) ----
    Company("IPG", "Interpublic Group", "Communication Services", "Advertising"),
    Company("OMC", "Omnicom Group", "Communication Services", "Advertising"),

    # ---- Consumer Staples (expansion: tobacco, consumer health) ----
    Company("PM", "Philip Morris International", "Consumer Staples", "Tobacco"),
    Company("MO", "Altria Group", "Consumer Staples", "Tobacco"),
    Company("KVUE", "Kenvue", "Consumer Staples", "Consumer Health"),

    # ---- Industrials (expansion: building systems, logistics, airlines) ----
    Company("CARR", "Carrier Global", "Industrials", "HVAC"),
    Company("OTIS", "Otis Worldwide", "Industrials", "Elevators/Escalators"),
    Company("JCI", "Johnson Controls", "Industrials", "Building Products"),
    Company("FTV", "Fortive Corp", "Industrials", "Industrial Technology"),
    Company("ROP", "Roper Technologies", "Industrials", "Diversified Industrial Software"),
    Company("IEX", "IDEX Corp", "Industrials", "Fluidics/Industrial Equipment"),
    Company("MAS", "Masco Corp", "Industrials", "Building Products"),
    Company("BLDR", "Builders FirstSource", "Industrials", "Building Materials Distribution"),
    Company("JBHT", "J.B. Hunt Transport", "Industrials", "Trucking"),
    Company("CHRW", "C.H. Robinson Worldwide", "Industrials", "Logistics"),
    Company("EXPD", "Expeditors International", "Industrials", "Logistics"),
    Company("ALK", "Alaska Air Group", "Industrials", "Airlines"),
    Company("JBLU", "JetBlue Airways", "Industrials", "Airlines"),
    Company("TXT", "Textron", "Industrials", "Aerospace/Industrial"),
    Company("SNA", "Snap-on", "Industrials", "Professional Tools"),

    # ---- Materials (expansion) ----
    Company("VMC", "Vulcan Materials", "Materials", "Construction Aggregates"),
    Company("MLM", "Martin Marietta Materials", "Materials", "Construction Aggregates"),
    Company("PPG", "PPG Industries", "Materials", "Paints & Coatings"),
    Company("ECL", "Ecolab", "Materials", "Water/Hygiene Solutions"),
    Company("ALLE", "Allegion", "Materials", "Security Products"),

    # ---- Financials (expansion: brokers, asset managers, exchanges) ----
    Company("AJG", "Arthur J. Gallagher", "Financials", "Insurance Brokerage"),
    Company("ERIE", "Erie Indemnity", "Financials", "Insurance"),
    Company("L", "Loews Corp", "Financials", "Insurance/Diversified Holding"),
    Company("RJF", "Raymond James Financial", "Financials", "Brokerage"),
    Company("IVZ", "Invesco", "Financials", "Asset Management"),
    Company("MKTX", "MarketAxess", "Financials", "Fixed Income Trading Platform"),

    # ---- Healthcare (expansion: devices, diagnostics, distribution) ----
    Company("RMD", "ResMed", "Healthcare", "Sleep Apnea Devices"),
    Company("COO", "Cooper Companies", "Healthcare", "Medical Devices"),
    Company("WST", "West Pharmaceutical Services", "Healthcare", "Drug Delivery Packaging"),
    Company("MTD", "Mettler-Toledo", "Healthcare", "Lab Instruments"),
    Company("WAT", "Waters Corp", "Healthcare", "Lab Instruments"),
    Company("A", "Agilent Technologies", "Healthcare", "Lab Instruments"),
    Company("BDX", "Becton Dickinson", "Healthcare", "Medical Devices"),
    Company("STE", "Steris", "Healthcare", "Sterilization/Medical Products"),
    Company("DGX", "Quest Diagnostics", "Healthcare", "Diagnostics"),
    Company("LH", "Labcorp Holdings", "Healthcare", "Diagnostics"),
    Company("CAH", "Cardinal Health", "Healthcare", "Pharma Distribution"),
    Company("MCK", "McKesson Corp", "Healthcare", "Pharma Distribution"),
    Company("COR", "Cencora", "Healthcare", "Pharma Distribution"),

    # ---- Real Estate (expansion) ----
    Company("ARE", "Alexandria Real Estate Equities", "Real Estate", "Life Science REIT"),
    Company("SBAC", "SBA Communications", "Real Estate", "Cell Tower REIT"),
    Company("REG", "Regency Centers", "Real Estate", "Retail REIT"),
    Company("KIM", "Kimco Realty", "Real Estate", "Retail REIT"),
    Company("FRT", "Federal Realty Investment Trust", "Real Estate", "Retail REIT"),
    Company("HST", "Host Hotels & Resorts", "Real Estate", "Hotel REIT"),
    Company("MAA", "Mid-America Apartment Communities", "Real Estate", "Residential REIT"),
    Company("UDR", "UDR Inc", "Real Estate", "Residential REIT"),

    # ---- Energy (expansion: midstream) ----
    Company("KMI", "Kinder Morgan", "Energy", "Midstream Pipelines"),
    Company("WMB", "Williams Companies", "Energy", "Midstream Pipelines"),
    Company("OKE", "ONEOK", "Energy", "Midstream Pipelines"),
    Company("ET", "Energy Transfer", "Energy", "Midstream Pipelines"),
    Company("TRGP", "Targa Resources", "Energy", "Midstream Pipelines"),

    # ---- Utilities (expansion) ----
    Company("PPL", "PPL Corp", "Utilities", "Electric Utility"),
    Company("FE", "FirstEnergy", "Utilities", "Electric Utility"),
    Company("ES", "Eversource Energy", "Utilities", "Electric Utility"),
    Company("ATO", "Atmos Energy", "Utilities", "Gas Utility"),
    Company("CMS", "CMS Energy", "Utilities", "Electric/Gas Utility"),
    Company("CNP", "CenterPoint Energy", "Utilities", "Electric/Gas Utility"),
    Company("NI", "NiSource", "Utilities", "Gas/Electric Utility"),
    Company("LNT", "Alliant Energy", "Utilities", "Electric Utility"),

    # ---- International e-commerce / internet ----
    Company("MELI", "MercadoLibre", "Consumer Discretionary", "Latin America E-Commerce"),
    Company("SE", "Sea Limited", "Consumer Discretionary", "SE Asia E-Commerce/Gaming"),
    Company("CPNG", "Coupang", "Consumer Discretionary", "Korea E-Commerce"),
    Company("BIDU", "Baidu", "Communication Services", "China Search/AI"),
    Company("PDD", "PDD Holdings", "Consumer Discretionary", "China E-Commerce"),
    Company("JD", "JD.com", "Consumer Discretionary", "China E-Commerce"),
    Company("BABA", "Alibaba Group", "Consumer Discretionary", "China E-Commerce"),
]

TICKERS = [c.ticker for c in COMPANIES]
COMPANY_BY_TICKER = {c.ticker: c for c in COMPANIES}

EDGES: list[Edge] = [
    # ---- Semiconductor supply chain (the densest cluster) ----
    Edge("TSM", "AAPL", "supplier", 0.9, "Fabs Apple Silicon (A/M-series)"),
    Edge("TSM", "NVDA", "supplier", 0.9, "Fabs Nvidia GPUs"),
    Edge("TSM", "AMD", "supplier", 0.85, "Fabs AMD CPUs/GPUs"),
    Edge("TSM", "QCOM", "supplier", 0.7, "Fabs Snapdragon chips"),
    Edge("TSM", "AVGO", "supplier", 0.6, "Foundry partner"),
    Edge("ASML", "TSM", "supplier", 0.85, "EUV lithography systems"),
    Edge("ASML", "INTC", "supplier", 0.6, "EUV lithography systems"),
    Edge("ASML", "MU", "supplier", 0.5, "Lithography for memory fabs"),
    Edge("AMAT", "TSM", "supplier", 0.6, "Wafer fab equipment"),
    Edge("AMAT", "INTC", "supplier", 0.55, "Wafer fab equipment"),
    Edge("AMAT", "MU", "supplier", 0.5, "Wafer fab equipment"),
    Edge("LRCX", "TSM", "supplier", 0.55, "Etch/deposition equipment"),
    Edge("LRCX", "MU", "supplier", 0.55, "Etch/deposition equipment"),
    Edge("KLAC", "TSM", "supplier", 0.5, "Process control equipment"),
    Edge("NVDA", "MSFT", "customer", 0.8, "Azure AI GPU purchases"),
    Edge("NVDA", "AMZN", "customer", 0.75, "AWS AI GPU purchases"),
    Edge("NVDA", "GOOGL", "customer", 0.7, "Google Cloud AI GPU purchases"),
    Edge("NVDA", "META", "customer", 0.75, "Meta AI training cluster GPU purchases"),
    Edge("NVDA", "SMCI", "partner", 0.6, "Reference server design partner"),
    Edge("NVDA", "DELL", "partner", 0.5, "AI server integration partner"),
    Edge("NVDA", "ARM", "partner", 0.4, "Grace CPU built on Arm architecture"),
    Edge("NVDA", "AMD", "competitor", 0.8, "GPU/AI accelerator rivalry"),
    Edge("NVDA", "INTC", "competitor", 0.5, "Data-center compute rivalry"),
    Edge("AMD", "MSFT", "customer", 0.5, "Azure CPU/GPU purchases"),
    Edge("AMD", "AMZN", "customer", 0.5, "AWS CPU/GPU purchases"),
    Edge("INTC", "DELL", "supplier", 0.5, "CPUs for PCs/servers"),
    Edge("INTC", "HPQ", "supplier", 0.45, "CPUs for PCs"),
    Edge("INTC", "AMD", "competitor", 0.8, "x86 CPU rivalry"),
    Edge("QCOM", "AAPL", "supplier", 0.5, "Modem chips (iPhone)"),
    Edge("ARM", "QCOM", "supplier", 0.6, "Chip architecture licensing"),
    Edge("ARM", "NVDA", "supplier", 0.4, "Chip architecture licensing"),
    Edge("ARM", "AAPL", "supplier", 0.5, "Chip architecture licensing"),
    Edge("MU", "AAPL", "supplier", 0.5, "Memory/storage chips"),
    Edge("MU", "DELL", "supplier", 0.4, "Memory/storage chips"),
    Edge("MU", "SMCI", "supplier", 0.4, "Memory for AI servers"),
    Edge("TXN", "AAPL", "supplier", 0.3, "Analog/power chips"),
    Edge("MRVL", "AMZN", "customer", 0.45, "Custom AI silicon for AWS"),
    Edge("MRVL", "MSFT", "customer", 0.4, "Custom AI networking silicon"),
    Edge("AVGO", "AAPL", "supplier", 0.5, "RF/wireless chips"),
    Edge("AVGO", "GOOGL", "customer", 0.5, "Custom AI accelerators (TPU-adjacent ASICs)"),
    Edge("SMCI", "NVDA", "customer", 0.7, "Buys GPUs to build AI servers"),
    Edge("DELL", "NVDA", "customer", 0.6, "Buys GPUs to build AI servers"),
    Edge("HPE", "NVDA", "customer", 0.5, "Buys GPUs to build AI servers"),
    Edge("SMCI", "DELL", "competitor", 0.4, "AI server rivalry"),
    Edge("SMCI", "HPE", "competitor", 0.4, "AI server rivalry"),
    Edge("DELL", "HPQ", "competitor", 0.4, "PC/hardware rivalry"),
    Edge("ON", "TSLA", "supplier", 0.4, "Power semiconductors for EVs"),
    Edge("ADI", "AAPL", "supplier", 0.3, "Analog/mixed-signal chips"),

    # ---- Big Tech platform web ----
    Edge("GOOGL", "AAPL", "partner", 0.6, "Default search deal on iOS/Safari"),
    Edge("GOOGL", "AAPL", "competitor", 0.5, "Android vs iOS"),
    Edge("MSFT", "GOOGL", "competitor", 0.6, "Cloud, search (Bing/Copilot) rivalry"),
    Edge("MSFT", "AMZN", "competitor", 0.7, "Azure vs AWS cloud rivalry"),
    Edge("GOOGL", "AMZN", "competitor", 0.6, "Google Cloud vs AWS rivalry"),
    Edge("AMZN", "MSFT", "competitor", 0.5, "Cloud enterprise rivalry"),
    Edge("META", "GOOGL", "competitor", 0.6, "Digital ad market rivalry"),
    Edge("META", "AAPL", "competitor", 0.35, "AR/VR and app-tracking tension"),
    Edge("ORCL", "MSFT", "competitor", 0.4, "Enterprise cloud/database rivalry"),
    Edge("CRM", "MSFT", "competitor", 0.4, "CRM/enterprise SaaS rivalry"),
    Edge("CRM", "ORCL", "competitor", 0.4, "Enterprise SaaS rivalry"),
    Edge("ADBE", "MSFT", "competitor", 0.3, "Creative/productivity software overlap"),
    Edge("NOW", "CRM", "competitor", 0.4, "Enterprise workflow software rivalry"),
    Edge("SNOW", "MSFT", "competitor", 0.4, "Data cloud vs Azure/Fabric rivalry"),
    Edge("SNOW", "AMZN", "competitor", 0.35, "Data cloud vs Redshift rivalry"),
    Edge("PLTR", "MSFT", "competitor", 0.3, "Enterprise/gov analytics overlap"),
    Edge("PLTR", "SNOW", "competitor", 0.3, "Data analytics overlap"),
    Edge("SHOP", "AMZN", "competitor", 0.5, "E-commerce platform rivalry"),
    Edge("UBER", "ABNB", "partner", 0.2, "Travel/mobility ecosystem adjacency"),
    Edge("NFLX", "DIS", "competitor", 0.6, "Streaming subscriber rivalry"),
    Edge("NFLX", "AMZN", "competitor", 0.4, "Streaming rivalry (Prime Video)"),
    Edge("DIS", "CMCSA", "competitor", 0.4, "Streaming/media rivalry"),
    Edge("PANW", "CRWD", "competitor", 0.7, "Cybersecurity platform rivalry"),
    Edge("PANW", "NET", "competitor", 0.3, "Security/edge overlap"),
    Edge("CRWD", "MSFT", "competitor", 0.35, "Endpoint security rivalry (Defender)"),
    Edge("NET", "AMZN", "competitor", 0.3, "Edge/CDN vs CloudFront rivalry"),
    Edge("DDOG", "MSFT", "competitor", 0.25, "Cloud observability overlap"),

    # ---- Payments / Financials ----
    Edge("V", "MA", "competitor", 0.8, "Card network duopoly rivalry"),
    Edge("V", "PYPL", "competitor", 0.4, "Digital payments overlap"),
    Edge("MA", "PYPL", "competitor", 0.4, "Digital payments overlap"),
    Edge("V", "AXP", "competitor", 0.4, "Payments network rivalry"),
    Edge("MA", "AXP", "competitor", 0.4, "Payments network rivalry"),
    Edge("V", "JPM", "partner", 0.4, "Card issuing partnership"),
    Edge("MA", "BAC", "partner", 0.4, "Card issuing partnership"),
    Edge("JPM", "BAC", "competitor", 0.6, "Retail/commercial banking rivalry"),
    Edge("JPM", "GS", "competitor", 0.5, "Investment banking rivalry"),
    Edge("GS", "MS", "competitor", 0.7, "Investment banking/trading rivalry"),
    Edge("BAC", "C", "competitor", 0.5, "Retail banking rivalry"),
    Edge("JPM", "C", "competitor", 0.5, "Global banking rivalry"),
    Edge("PYPL", "SHOP", "partner", 0.3, "Checkout/payments integration"),

    # ---- EV / Auto cluster ----
    Edge("TSLA", "GM", "competitor", 0.6, "EV market rivalry"),
    Edge("TSLA", "F", "competitor", 0.6, "EV market rivalry"),
    Edge("TSLA", "RIVN", "competitor", 0.5, "EV market rivalry"),
    Edge("TSLA", "LCID", "competitor", 0.45, "EV market rivalry"),
    Edge("TSLA", "TM", "competitor", 0.4, "EV/hybrid market rivalry"),
    Edge("GM", "F", "competitor", 0.6, "US auto rivalry"),
    Edge("GM", "TM", "competitor", 0.5, "Global auto rivalry"),
    Edge("F", "STLA", "competitor", 0.4, "US/Europe auto rivalry"),
    Edge("RIVN", "LCID", "competitor", 0.5, "EV startup rivalry"),
    Edge("ALB", "TSLA", "supplier", 0.5, "Lithium for battery cells"),
    Edge("ALB", "GM", "supplier", 0.35, "Lithium for battery cells"),
    Edge("ALB", "F", "supplier", 0.3, "Lithium for battery cells"),
    Edge("ON", "GM", "supplier", 0.3, "Power semiconductors for EVs"),

    # ---- Retail cluster ----
    Edge("WMT", "TGT", "competitor", 0.7, "Mass retail rivalry"),
    Edge("WMT", "COST", "competitor", 0.6, "Retail/wholesale rivalry"),
    Edge("WMT", "AMZN", "competitor", 0.7, "Retail/e-commerce rivalry"),
    Edge("TGT", "COST", "competitor", 0.5, "Retail rivalry"),
    Edge("TGT", "AMZN", "competitor", 0.6, "Retail/e-commerce rivalry"),
    Edge("HD", "LOW", "competitor", 0.8, "Home improvement retail rivalry"),
    Edge("SBUX", "MCD", "competitor", 0.5, "Restaurant/coffee rivalry"),
    Edge("KO", "PEP", "competitor", 0.8, "Beverage rivalry"),
    Edge("PG", "KO", "partner", 0.1, "Shared retail shelf/distribution"),
    Edge("NKE", "TGT", "customer", 0.2, "Retail distribution"),
    Edge("FDX", "UPS", "competitor", 0.75, "Parcel/logistics rivalry"),
    Edge("FDX", "AMZN", "competitor", 0.4, "Logistics rivalry (Amazon Logistics)"),
    Edge("UPS", "AMZN", "competitor", 0.4, "Logistics rivalry (Amazon Logistics)"),
    Edge("AMZN", "WMT", "competitor", 0.7, "E-commerce vs mass retail rivalry"),

    # ---- Energy cluster ----
    Edge("SLB", "XOM", "supplier", 0.5, "Oilfield services"),
    Edge("SLB", "CVX", "supplier", 0.5, "Oilfield services"),
    Edge("SLB", "COP", "supplier", 0.45, "Oilfield services"),
    Edge("XOM", "CVX", "competitor", 0.6, "Integrated oil & gas rivalry"),
    Edge("XOM", "COP", "competitor", 0.45, "E&P rivalry"),
    Edge("CVX", "COP", "competitor", 0.45, "E&P rivalry"),

    # ---- Airlines / Aerospace ----
    Edge("BA", "DAL", "supplier", 0.5, "Aircraft manufacturer"),
    Edge("BA", "UAL", "supplier", 0.5, "Aircraft manufacturer"),
    Edge("BA", "AAL", "supplier", 0.5, "Aircraft manufacturer"),
    Edge("BA", "LUV", "supplier", 0.55, "Sole 737 supplier to Southwest"),
    Edge("DAL", "UAL", "competitor", 0.6, "US airline rivalry"),
    Edge("DAL", "AAL", "competitor", 0.6, "US airline rivalry"),
    Edge("UAL", "AAL", "competitor", 0.6, "US airline rivalry"),
    Edge("LUV", "DAL", "competitor", 0.4, "US airline rivalry"),
    Edge("GE", "BA", "supplier", 0.45, "Jet engines (GE Aerospace)"),
    Edge("HON", "BA", "supplier", 0.3, "Avionics & aerospace systems"),

    # ---- Telecom / Media ----
    Edge("T", "VZ", "competitor", 0.7, "Wireless carrier rivalry"),
    Edge("T", "TMUS", "competitor", 0.6, "Wireless carrier rivalry"),
    Edge("VZ", "TMUS", "competitor", 0.6, "Wireless carrier rivalry"),
    Edge("CMCSA", "T", "competitor", 0.35, "Broadband/media rivalry"),
    Edge("AAPL", "T", "partner", 0.2, "iPhone carrier distribution"),
    Edge("AAPL", "VZ", "partner", 0.2, "iPhone carrier distribution"),
    Edge("AAPL", "TMUS", "partner", 0.2, "iPhone carrier distribution"),

    # ---- Healthcare / Pharma ----
    Edge("UNH", "CVS", "competitor", 0.5, "Managed care/pharmacy benefits rivalry"),
    Edge("JNJ", "PFE", "competitor", 0.4, "Pharma rivalry"),
    Edge("JNJ", "MRK", "competitor", 0.4, "Pharma rivalry"),
    Edge("PFE", "MRK", "competitor", 0.5, "Pharma rivalry"),
    Edge("LLY", "MRK", "competitor", 0.4, "Pharma rivalry (metabolic/oncology)"),
    Edge("LLY", "ABBV", "competitor", 0.4, "Pharma rivalry (immunology)"),
    Edge("ABBV", "JNJ", "competitor", 0.4, "Pharma rivalry"),
    Edge("CVS", "WMT", "competitor", 0.3, "Retail pharmacy/front-store rivalry"),

    # ---- Industrials ----
    Edge("CAT", "UNP", "customer", 0.2, "Rail-hauled heavy equipment demand link"),
    Edge("HON", "GE", "competitor", 0.4, "Industrial conglomerate rivalry"),
    Edge("UNP", "FDX", "partner", 0.2, "Intermodal freight partner"),

    # ---- Software / SaaS / chip-design tooling ----
    Edge("INTU", "CRM", "competitor", 0.2, "Business software overlap"),
    Edge("ADSK", "NVDA", "partner", 0.3, "GPU-accelerated design software"),
    Edge("WDAY", "NOW", "competitor", 0.4, "Enterprise workflow SaaS rivalry"),
    Edge("WDAY", "CRM", "competitor", 0.3, "Enterprise SaaS rivalry (HCM)"),
    Edge("TEAM", "MSFT", "competitor", 0.35, "Team collaboration/project software rivalry"),
    Edge("MDB", "SNOW", "competitor", 0.3, "Data platform overlap"),
    Edge("MDB", "ORCL", "competitor", 0.3, "Database rivalry"),
    Edge("ZS", "PANW", "competitor", 0.4, "Cloud security rivalry"),
    Edge("ZS", "CRWD", "competitor", 0.35, "Cloud security rivalry"),
    Edge("OKTA", "MSFT", "competitor", 0.4, "Identity management rivalry (Entra ID)"),
    Edge("OKTA", "CRWD", "partner", 0.2, "Identity + endpoint security integration"),
    Edge("DOCU", "ADBE", "competitor", 0.3, "E-signature rivalry (Adobe Sign)"),
    Edge("TTD", "GOOGL", "competitor", 0.4, "Programmatic ad tech rivalry"),
    Edge("TTD", "META", "competitor", 0.35, "Digital ad market rivalry"),
    Edge("CDNS", "SNPS", "competitor", 0.7, "EDA / chip-design software duopoly"),
    Edge("CDNS", "NVDA", "supplier", 0.4, "Chip design software (EDA tools)"),
    Edge("CDNS", "AMD", "supplier", 0.3, "Chip design software (EDA tools)"),
    Edge("SNPS", "TSM", "supplier", 0.3, "Chip design software (EDA tools)"),
    Edge("SNPS", "INTC", "supplier", 0.3, "Chip design software (EDA tools)"),
    Edge("FTNT", "PANW", "competitor", 0.5, "Network security rivalry"),
    Edge("FTNT", "CRWD", "competitor", 0.35, "Cybersecurity rivalry"),
    Edge("TER", "TSM", "supplier", 0.3, "Semiconductor test equipment"),
    Edge("TER", "NVDA", "supplier", 0.25, "Semiconductor test equipment"),
    Edge("SWKS", "AAPL", "supplier", 0.4, "RF chips for iPhone"),
    Edge("SWKS", "QRVO", "competitor", 0.5, "RF semiconductor rivalry"),
    Edge("QRVO", "AAPL", "supplier", 0.3, "RF chips for iPhone"),

    # ---- Consumer internet / entertainment ----
    Edge("SPOT", "AAPL", "competitor", 0.4, "Music streaming rivalry (Apple Music)"),
    Edge("EA", "TTWO", "competitor", 0.5, "Video game publisher rivalry"),
    Edge("RBLX", "EA", "competitor", 0.25, "Gaming/entertainment overlap"),
    Edge("RBLX", "TTWO", "competitor", 0.25, "Gaming/entertainment overlap"),
    Edge("PINS", "META", "competitor", 0.4, "Social/ad platform rivalry"),
    Edge("PINS", "SNAP", "competitor", 0.35, "Social media rivalry"),
    Edge("SNAP", "META", "competitor", 0.6, "Social media rivalry"),
    Edge("MTCH", "META", "competitor", 0.2, "Social discovery overlap"),
    Edge("EBAY", "AMZN", "competitor", 0.5, "E-commerce platform rivalry"),
    Edge("EBAY", "ETSY", "competitor", 0.4, "Online marketplace rivalry"),
    Edge("ETSY", "AMZN", "competitor", 0.4, "E-commerce platform rivalry"),
    Edge("ETSY", "SHOP", "competitor", 0.2, "E-commerce platform overlap"),
    Edge("BKNG", "EXPE", "competitor", 0.6, "Online travel agency rivalry"),
    Edge("BKNG", "ABNB", "competitor", 0.4, "Travel booking rivalry"),
    Edge("EXPE", "ABNB", "competitor", 0.35, "Travel booking rivalry"),
    Edge("MAR", "HLT", "competitor", 0.7, "Hotel chain rivalry"),
    Edge("MAR", "BKNG", "partner", 0.2, "Distribution partnership"),
    Edge("HLT", "BKNG", "partner", 0.2, "Distribution partnership"),
    Edge("LYV", "SPOT", "partner", 0.2, "Live event ticketing/streaming adjacency"),
    Edge("CCL", "RCL", "competitor", 0.7, "Cruise line rivalry"),
    Edge("WBD", "DIS", "competitor", 0.5, "Streaming/media rivalry"),
    Edge("WBD", "NFLX", "competitor", 0.4, "Streaming subscriber rivalry"),
    Edge("WBD", "CMCSA", "competitor", 0.35, "Media conglomerate rivalry"),
    Edge("PARA", "DIS", "competitor", 0.4, "Streaming/media rivalry"),
    Edge("PARA", "WBD", "competitor", 0.4, "Media conglomerate rivalry"),
    Edge("PARA", "NFLX", "competitor", 0.35, "Streaming subscriber rivalry"),

    # ---- Retail / Apparel ----
    Edge("LULU", "NKE", "competitor", 0.5, "Athletic apparel rivalry"),
    Edge("TJX", "ROST", "competitor", 0.6, "Off-price retail rivalry"),
    Edge("TJX", "WMT", "competitor", 0.2, "Discount retail overlap"),
    Edge("ROST", "TGT", "competitor", 0.2, "Discount retail overlap"),

    # ---- Healthcare / Pharma / Biotech ----
    Edge("BMY", "PFE", "competitor", 0.35, "Pharma rivalry"),
    Edge("BMY", "MRK", "competitor", 0.35, "Pharma rivalry (oncology)"),
    Edge("GILD", "VRTX", "competitor", 0.3, "Biotech rivalry (antivirals)"),
    Edge("GILD", "REGN", "competitor", 0.25, "Biotech rivalry"),
    Edge("AMGN", "REGN", "competitor", 0.35, "Biotech rivalry (immunology)"),
    Edge("AMGN", "VRTX", "competitor", 0.25, "Biotech rivalry"),
    Edge("REGN", "LLY", "competitor", 0.3, "Pharma rivalry (eye/metabolic disease)"),
    Edge("VRTX", "REGN", "competitor", 0.25, "Biotech rivalry"),
    Edge("MDT", "SYK", "competitor", 0.5, "Medical device rivalry"),
    Edge("MDT", "ISRG", "competitor", 0.35, "Surgical device rivalry"),
    Edge("SYK", "ISRG", "competitor", 0.35, "Surgical device rivalry"),
    Edge("DHR", "TMO", "competitor", 0.5, "Life sciences tools/instruments rivalry"),
    Edge("CI", "UNH", "competitor", 0.4, "Health insurance rivalry"),
    Edge("CI", "ELV", "competitor", 0.4, "Health insurance rivalry"),
    Edge("CI", "HUM", "competitor", 0.35, "Health insurance rivalry"),
    Edge("ELV", "UNH", "competitor", 0.4, "Health insurance rivalry"),
    Edge("ELV", "HUM", "competitor", 0.35, "Health insurance rivalry"),
    Edge("HUM", "UNH", "competitor", 0.4, "Health insurance rivalry (Medicare Advantage)"),

    # ---- Financials (asset managers, exchanges, big banks) ----
    Edge("SCHW", "MS", "competitor", 0.3, "Brokerage/wealth management overlap"),
    Edge("SCHW", "GS", "competitor", 0.25, "Wealth management overlap"),
    Edge("BLK", "BX", "competitor", 0.3, "Asset management overlap"),
    Edge("BLK", "SCHW", "partner", 0.2, "ETF distribution partnership"),
    Edge("SPGI", "ICE", "competitor", 0.2, "Financial data/analytics overlap"),
    Edge("ICE", "CME", "competitor", 0.6, "Derivatives exchange rivalry"),
    Edge("COF", "AXP", "competitor", 0.4, "Credit card issuer rivalry"),
    Edge("COF", "V", "partner", 0.3, "Card network partnership"),
    Edge("COF", "MA", "partner", 0.3, "Card network partnership"),
    Edge("USB", "WFC", "competitor", 0.4, "Regional/national banking rivalry"),
    Edge("USB", "PNC", "competitor", 0.4, "Regional banking rivalry"),
    Edge("WFC", "JPM", "competitor", 0.5, "National banking rivalry"),
    Edge("WFC", "BAC", "competitor", 0.5, "National banking rivalry"),
    Edge("PNC", "USB", "competitor", 0.4, "Regional banking rivalry"),
    Edge("PNC", "BAC", "competitor", 0.3, "Regional/national banking rivalry"),

    # ---- Energy (refiners, E&P, oilfield services) ----
    Edge("OXY", "XOM", "competitor", 0.3, "E&P rivalry (Permian Basin)"),
    Edge("OXY", "COP", "competitor", 0.3, "E&P rivalry"),
    Edge("PSX", "VLO", "competitor", 0.5, "Refining rivalry"),
    Edge("PSX", "MPC", "competitor", 0.5, "Refining rivalry"),
    Edge("MPC", "VLO", "competitor", 0.5, "Refining rivalry"),
    Edge("EOG", "COP", "competitor", 0.4, "E&P rivalry (shale)"),
    Edge("EOG", "DVN", "competitor", 0.4, "E&P rivalry (shale)"),
    Edge("DVN", "COP", "competitor", 0.35, "E&P rivalry"),
    Edge("HAL", "SLB", "competitor", 0.6, "Oilfield services rivalry"),
    Edge("HAL", "BKR", "competitor", 0.5, "Oilfield services rivalry"),
    Edge("BKR", "SLB", "competitor", 0.5, "Oilfield services rivalry"),
    Edge("BKR", "XOM", "supplier", 0.3, "Oilfield equipment & services"),

    # ---- Materials ----
    Edge("LIN", "TSM", "supplier", 0.3, "Industrial/specialty gases for chip fabs"),
    Edge("SHW", "HD", "customer", 0.3, "Paint sold through home improvement retail"),
    Edge("SHW", "LOW", "customer", 0.3, "Paint sold through home improvement retail"),
    Edge("NEM", "FCX", "competitor", 0.25, "Metals mining overlap"),
    Edge("FCX", "TSLA", "supplier", 0.3, "Copper for EV/battery production"),
    Edge("DOW", "DD", "competitor", 0.5, "Specialty chemicals rivalry"),
    Edge("DOW", "LIN", "competitor", 0.2, "Industrial chemicals/gases overlap"),

    # ---- Consumer Staples ----
    Edge("MDLZ", "GIS", "competitor", 0.35, "Packaged food rivalry"),
    Edge("MDLZ", "KHC", "competitor", 0.3, "Packaged food rivalry"),
    Edge("CL", "PG", "competitor", 0.5, "Household products rivalry"),
    Edge("CL", "KMB", "competitor", 0.4, "Household/personal care rivalry"),
    Edge("KMB", "PG", "competitor", 0.5, "Household products rivalry"),
    Edge("GIS", "KHC", "competitor", 0.35, "Packaged food rivalry"),
    Edge("KHC", "MDLZ", "competitor", 0.3, "Packaged food rivalry"),
    Edge("MNST", "KO", "competitor", 0.3, "Beverage rivalry (energy drinks)"),
    Edge("MNST", "PEP", "competitor", 0.3, "Beverage rivalry (energy drinks)"),
    Edge("CLX", "PG", "competitor", 0.3, "Household products rivalry"),
    Edge("CLX", "CL", "competitor", 0.3, "Household products rivalry"),

    # ---- Utilities / REITs ----
    Edge("NEE", "DUK", "competitor", 0.3, "Regulated electric utility overlap"),
    Edge("NEE", "SO", "competitor", 0.25, "Regulated electric utility overlap"),
    Edge("DUK", "SO", "competitor", 0.3, "Regulated electric utility overlap"),
    Edge("DUK", "AEP", "competitor", 0.3, "Regulated electric utility overlap"),
    Edge("SO", "AEP", "competitor", 0.3, "Regulated electric utility overlap"),
    Edge("PLD", "AMZN", "customer", 0.4, "Warehouse/logistics real estate tenant"),
    Edge("PLD", "FDX", "customer", 0.25, "Warehouse/logistics real estate tenant"),
    Edge("AMT", "T", "customer", 0.35, "Cell tower leasing tenant"),
    Edge("AMT", "VZ", "customer", 0.35, "Cell tower leasing tenant"),
    Edge("AMT", "TMUS", "customer", 0.3, "Cell tower leasing tenant"),
    Edge("EQIX", "DLR", "competitor", 0.6, "Data center REIT rivalry"),
    Edge("EQIX", "MSFT", "customer", 0.3, "Cloud provider colocation tenant"),
    Edge("DLR", "AMZN", "customer", 0.3, "Cloud provider colocation tenant"),
    Edge("DLR", "GOOGL", "customer", 0.25, "Cloud provider colocation tenant"),

    # ---- Industrials (defense, machinery, diversified) ----
    Edge("LMT", "RTX", "competitor", 0.5, "Defense contractor rivalry"),
    Edge("LMT", "NOC", "competitor", 0.45, "Defense contractor rivalry"),
    Edge("LMT", "GD", "competitor", 0.4, "Defense contractor rivalry"),
    Edge("RTX", "NOC", "competitor", 0.4, "Defense contractor rivalry"),
    Edge("RTX", "BA", "supplier", 0.4, "Jet engines (Pratt & Whitney)"),
    Edge("RTX", "GE", "competitor", 0.4, "Jet engine manufacturer rivalry"),
    Edge("NOC", "GD", "competitor", 0.4, "Defense contractor rivalry"),
    Edge("GD", "LMT", "competitor", 0.4, "Defense contractor rivalry"),
    Edge("DE", "CAT", "competitor", 0.6, "Heavy machinery/equipment rivalry"),
    Edge("MMM", "HON", "competitor", 0.35, "Diversified industrial rivalry"),
    Edge("MMM", "GE", "competitor", 0.3, "Diversified industrial rivalry"),
    Edge("ITW", "MMM", "competitor", 0.25, "Diversified industrial overlap"),
    Edge("ITW", "HON", "competitor", 0.25, "Diversified industrial overlap"),
    Edge("EMR", "HON", "competitor", 0.35, "Industrial automation rivalry"),
    Edge("EMR", "ITW", "competitor", 0.25, "Industrial automation overlap"),
    Edge("APTV", "TSLA", "supplier", 0.4, "Vehicle electrical architecture/software"),
    Edge("APTV", "GM", "supplier", 0.35, "Auto electronics/components"),
    Edge("APTV", "F", "supplier", 0.35, "Auto electronics/components"),
    Edge("APTV", "BWA", "competitor", 0.4, "Auto parts/tech rivalry"),
    Edge("BWA", "GM", "supplier", 0.3, "Powertrain/EV components"),
    Edge("BWA", "F", "supplier", 0.3, "Powertrain/EV components"),
    Edge("BWA", "TM", "supplier", 0.25, "Powertrain components"),

    # ---- Legacy tech (previously isolated nodes) ----
    Edge("IBM", "MSFT", "competitor", 0.3, "Enterprise IT/cloud services rivalry"),
    Edge("IBM", "ORCL", "competitor", 0.35, "Enterprise software/database rivalry"),
    Edge("IBM", "DELL", "competitor", 0.2, "Enterprise IT hardware/services overlap"),
    Edge("CSCO", "HPE", "competitor", 0.4, "Networking/enterprise hardware rivalry"),
    Edge("CSCO", "DELL", "competitor", 0.3, "Enterprise hardware rivalry"),
    Edge("CSCO", "NET", "competitor", 0.2, "Networking/edge infrastructure overlap"),

    # ---- Insurance ----
    Edge("AIG", "TRV", "competitor", 0.4, "Multiline/P&C insurance rivalry"),
    Edge("AIG", "ALL", "competitor", 0.35, "P&C insurance rivalry"),
    Edge("TRV", "ALL", "competitor", 0.4, "P&C insurance rivalry"),
    Edge("PGR", "ALL", "competitor", 0.55, "Auto insurance rivalry"),
    Edge("PGR", "TRV", "competitor", 0.35, "Auto/P&C insurance overlap"),
    Edge("MET", "PRU", "competitor", 0.55, "Life insurance rivalry"),
    Edge("MET", "AFL", "competitor", 0.3, "Life/supplemental insurance overlap"),
    Edge("PRU", "AFL", "competitor", 0.3, "Life/supplemental insurance overlap"),
    Edge("HIG", "TRV", "competitor", 0.4, "P&C insurance rivalry"),
    Edge("HIG", "AIG", "competitor", 0.3, "P&C/commercial insurance overlap"),
    Edge("AIG", "BLK", "partner", 0.2, "Asset management relationship for AIG's investment portfolio"),

    # ---- Homebuilders ----
    Edge("DHI", "LEN", "competitor", 0.6, "Homebuilding rivalry"),
    Edge("DHI", "PHM", "competitor", 0.55, "Homebuilding rivalry"),
    Edge("LEN", "PHM", "competitor", 0.55, "Homebuilding rivalry"),
    Edge("PHM", "NVR", "competitor", 0.4, "Homebuilding rivalry"),
    Edge("NVR", "DHI", "competitor", 0.35, "Homebuilding rivalry"),
    Edge("DHI", "SHW", "customer", 0.25, "Paint/coatings for new-build homes"),
    Edge("LEN", "SHW", "customer", 0.25, "Paint/coatings for new-build homes"),
    Edge("DHI", "HD", "customer", 0.2, "Building materials sourcing"),
    Edge("PHM", "LOW", "customer", 0.2, "Building materials sourcing"),

    # ---- Rail / Trucking ----
    Edge("CSX", "NSC", "competitor", 0.6, "Eastern US rail duopoly rivalry"),
    Edge("CSX", "UNP", "competitor", 0.35, "Freight rail overlap"),
    Edge("NSC", "UNP", "competitor", 0.35, "Freight rail overlap"),
    Edge("ODFL", "FDX", "competitor", 0.3, "Freight/logistics overlap"),
    Edge("ODFL", "UPS", "competitor", 0.3, "Freight/logistics overlap"),
    Edge("CSX", "UPS", "customer", 0.2, "Intermodal freight for parcel network"),
    Edge("NSC", "FDX", "customer", 0.2, "Intermodal freight for parcel network"),

    # ---- Metals & Mining ----
    Edge("NUE", "STLD", "competitor", 0.6, "Steel producer rivalry"),
    Edge("NUE", "AA", "competitor", 0.2, "Industrial metals overlap"),
    Edge("STLD", "AA", "competitor", 0.2, "Industrial metals overlap"),
    Edge("NUE", "CAT", "supplier", 0.3, "Steel for heavy equipment manufacturing"),
    Edge("NUE", "F", "supplier", 0.25, "Steel for auto manufacturing"),
    Edge("AA", "BA", "supplier", 0.3, "Aluminum for aircraft structures"),
    Edge("AA", "F", "supplier", 0.25, "Aluminum for auto bodies"),
    Edge("STLD", "DE", "supplier", 0.25, "Steel for agricultural/construction equipment"),

    # ---- Restaurants ----
    Edge("CMG", "YUM", "competitor", 0.4, "Fast-casual/QSR rivalry"),
    Edge("CMG", "MCD", "competitor", 0.4, "Fast-casual/QSR rivalry"),
    Edge("YUM", "MCD", "competitor", 0.5, "QSR rivalry"),
    Edge("DPZ", "YUM", "competitor", 0.35, "QSR/pizza delivery rivalry"),
    Edge("DPZ", "MCD", "competitor", 0.25, "QSR overlap"),
    Edge("CMG", "SBUX", "competitor", 0.15, "Fast-casual dining overlap"),

    # ---- Crypto-adjacent ----
    Edge("COIN", "MSTR", "competitor", 0.3, "Crypto-market exposure overlap"),
    Edge("COIN", "V", "partner", 0.25, "Crypto debit card issuing partnership"),
    Edge("COIN", "MA", "partner", 0.25, "Crypto card/payments partnership"),
    Edge("COIN", "PYPL", "competitor", 0.25, "Crypto trading/payments overlap"),
    Edge("MSTR", "NVDA", "customer", 0.1, "Bitcoin-mining-adjacent hardware demand (indirect)"),

    # ---- Agriculture ----
    Edge("ADM", "BG", "competitor", 0.6, "Agribusiness/grain trading rivalry"),
    Edge("ADM", "CTVA", "customer", 0.3, "Seed/crop-input sourcing for grain processing"),
    Edge("BG", "CTVA", "customer", 0.25, "Seed/crop-input sourcing"),
    Edge("CTVA", "DD", "competitor", 0.3, "Agricultural chemicals overlap (Corteva was spun off from DowDuPont)"),
    Edge("ADM", "DE", "customer", 0.2, "Farm equipment demand tied to grain-belt customers"),
    Edge("ADM", "KHC", "supplier", 0.3, "Agricultural ingredients for packaged food"),
    Edge("BG", "MDLZ", "supplier", 0.25, "Agricultural ingredients for packaged food"),

    # ---- Healthcare / Biotech (additional) ----
    Edge("BIIB", "MRNA", "competitor", 0.25, "Biotech R&D overlap"),
    Edge("BIIB", "REGN", "competitor", 0.35, "Biotech pipeline rivalry"),
    Edge("MRNA", "PFE", "competitor", 0.45, "mRNA vaccine rivalry"),
    Edge("MRNA", "JNJ", "competitor", 0.25, "Vaccine market overlap"),
    Edge("ZTS", "ISRG", "partner", 0.1, "Veterinary surgical technology adjacency"),
    Edge("BIIB", "LLY", "competitor", 0.2, "Neurology/Alzheimer's pipeline rivalry"),

    # ---- Regional Banks ----
    Edge("TFC", "FITB", "competitor", 0.5, "Regional bank rivalry"),
    Edge("TFC", "USB", "competitor", 0.4, "Regional bank overlap"),
    Edge("TFC", "PNC", "competitor", 0.4, "Regional bank overlap"),
    Edge("FITB", "USB", "competitor", 0.35, "Regional bank overlap"),
    Edge("FITB", "PNC", "competitor", 0.35, "Regional bank overlap"),
    Edge("TFC", "JPM", "competitor", 0.2, "Consumer/commercial banking overlap"),

    # ---- Media (additional) ----
    Edge("FOXA", "NWSA", "partner", 0.3, "Common Murdoch-family ownership lineage"),
    Edge("FOXA", "DIS", "competitor", 0.35, "Broadcast/media rivalry"),
    Edge("FOXA", "WBD", "competitor", 0.35, "Cable news/entertainment rivalry"),
    Edge("FOXA", "PARA", "competitor", 0.35, "Broadcast network rivalry"),
    Edge("NWSA", "CMCSA", "competitor", 0.2, "Media/publishing overlap"),

    # ---- Apparel / Luxury (additional) ----
    Edge("RL", "TPR", "competitor", 0.4, "Luxury/premium apparel rivalry"),
    Edge("RL", "NKE", "competitor", 0.2, "Apparel overlap"),
    Edge("TPR", "LULU", "competitor", 0.15, "Premium apparel/accessories overlap"),
    Edge("RL", "TJX", "customer", 0.15, "Off-price channel for excess inventory"),

    # ---- Packaging ----
    Edge("IP", "PKG", "competitor", 0.55, "Containerboard/packaging rivalry"),
    Edge("IP", "PG", "customer", 0.25, "Packaging supplier for consumer products"),
    Edge("PKG", "KHC", "customer", 0.25, "Packaging supplier for packaged food"),
    Edge("IP", "AMZN", "customer", 0.3, "Corrugated packaging for e-commerce shipping"),
    Edge("PKG", "MDLZ", "customer", 0.2, "Packaging supplier for packaged food"),

    # ---- Water Utility ----
    Edge("AWK", "NEE", "competitor", 0.1, "Regulated-utility sector overlap"),
    Edge("AWK", "DUK", "competitor", 0.1, "Regulated-utility sector overlap"),

    # ---- Real Estate / REITs (expansion) ----
    Edge("O", "SPG", "competitor", 0.2, "REIT sector overlap (retail-oriented)"),
    Edge("SPG", "TJX", "customer", 0.15, "Mall/outlet anchor tenant relationship"),
    Edge("SPG", "ROST", "customer", 0.15, "Mall/outlet anchor tenant relationship"),
    Edge("WELL", "VTR", "competitor", 0.45, "Healthcare REIT rivalry"),
    Edge("PSA", "EXR", "competitor", 0.55, "Self-storage REIT rivalry"),
    Edge("AVB", "EQR", "competitor", 0.5, "Residential REIT rivalry (coastal apartments)"),
    Edge("CCI", "AMT", "competitor", 0.55, "Cell tower REIT rivalry"),
    Edge("CCI", "T", "customer", 0.3, "Tower leasing to wireless carriers"),
    Edge("CCI", "VZ", "customer", 0.3, "Tower leasing to wireless carriers"),
    Edge("CCI", "TMUS", "customer", 0.3, "Tower leasing to wireless carriers"),
    Edge("IRM", "EQIX", "competitor", 0.15, "Data center / records storage overlap"),
    Edge("EQIX", "DLR", "competitor", 0.6, "Data center REIT rivalry"),

    # ---- Utilities (expansion) ----
    Edge("D", "DUK", "competitor", 0.35, "Southeast electric utility rivalry"),
    Edge("D", "SO", "competitor", 0.35, "Southeast electric utility rivalry"),
    Edge("EXC", "NEE", "competitor", 0.2, "Electric utility sector overlap"),
    Edge("EXC", "AEE", "competitor", 0.3, "Midwest electric utility rivalry"),
    Edge("ED", "DUK", "competitor", 0.15, "Electric utility sector overlap"),
    Edge("XEL", "AEE", "competitor", 0.3, "Midwest electric utility rivalry"),
    Edge("PEG", "D", "competitor", 0.25, "Northeast/Mid-Atlantic utility rivalry"),
    Edge("WEC", "XEL", "competitor", 0.3, "Midwest electric utility rivalry"),
    Edge("SRE", "AEP", "competitor", 0.2, "Multi-utility sector overlap"),

    # ---- Financials: regional banks, insurance brokers, asset managers, exchanges ----
    Edge("MTB", "FITB", "competitor", 0.4, "Regional bank rivalry"),
    Edge("RF", "CFG", "competitor", 0.4, "Regional bank rivalry"),
    Edge("KEY", "HBAN", "competitor", 0.45, "Midwest regional bank rivalry"),
    Edge("ZION", "KEY", "competitor", 0.25, "Regional bank sector overlap"),
    Edge("CINF", "TRV", "competitor", 0.3, "Property & casualty insurance rivalry"),
    Edge("AON", "MMC", "competitor", 0.55, "Insurance brokerage rivalry"),
    Edge("MMC", "WTW", "competitor", 0.5, "Insurance brokerage rivalry"),
    Edge("AON", "WTW", "competitor", 0.5, "Insurance brokerage rivalry"),
    Edge("TROW", "BEN", "competitor", 0.4, "Asset management rivalry"),
    Edge("TROW", "BLK", "competitor", 0.3, "Asset management rivalry"),
    Edge("STT", "BK", "competitor", 0.55, "Custody banking rivalry"),
    Edge("BK", "BLK", "partner", 0.15, "Custody/asset servicing relationship"),
    Edge("NDAQ", "ICE", "competitor", 0.5, "Financial exchange rivalry"),
    Edge("NDAQ", "CBOE", "competitor", 0.4, "Financial exchange rivalry"),
    Edge("CBOE", "ICE", "competitor", 0.3, "Financial exchange/derivatives rivalry"),

    # ---- Fintech / payments (expansion) ----
    Edge("SOFI", "UPST", "competitor", 0.25, "Fintech lending overlap"),
    Edge("SOFI", "AFRM", "competitor", 0.2, "Consumer fintech overlap"),
    Edge("AFRM", "PYPL", "competitor", 0.3, "Buy-now-pay-later overlap"),
    Edge("UPST", "COF", "competitor", 0.15, "Consumer lending overlap"),
    Edge("FI", "FIS", "competitor", 0.55, "Payments processing rivalry"),
    Edge("FIS", "GPN", "competitor", 0.45, "Payments processing rivalry"),
    Edge("FI", "GPN", "competitor", 0.45, "Payments processing rivalry"),
    Edge("XYZ", "PYPL", "competitor", 0.45, "Digital payments rivalry"),
    Edge("XYZ", "SOFI", "competitor", 0.2, "Consumer fintech overlap"),
    Edge("GPN", "MA", "partner", 0.2, "Card network processing partnership"),
    Edge("FI", "V", "partner", 0.2, "Card network processing partnership"),

    # ---- Healthcare (expansion) ----
    Edge("ABT", "MDT", "competitor", 0.4, "Medical devices rivalry"),
    Edge("BSX", "MDT", "competitor", 0.45, "Medical devices rivalry"),
    Edge("BSX", "ABT", "competitor", 0.35, "Medical devices rivalry"),
    Edge("EW", "MDT", "competitor", 0.35, "Cardiac devices rivalry"),
    Edge("EW", "ABT", "competitor", 0.3, "Structural heart devices rivalry"),
    Edge("ZBH", "SYK", "competitor", 0.5, "Orthopedic implants rivalry"),
    Edge("IDXX", "ZTS", "competitor", 0.25, "Animal health overlap"),
    Edge("HCA", "UNH", "customer", 0.15, "Hospital network / payer relationship"),
    Edge("DXCM", "MDT", "competitor", 0.35, "Diabetes/glucose monitoring rivalry"),
    Edge("ALGN", "SYK", "competitor", 0.1, "Medical device sector overlap"),
    Edge("VTRS", "PFE", "competitor", 0.2, "Generic/branded pharma overlap"),
    Edge("CNC", "MOH", "competitor", 0.5, "Medicaid managed care rivalry"),
    Edge("CNC", "UNH", "competitor", 0.3, "Managed care rivalry"),
    Edge("MOH", "ELV", "competitor", 0.3, "Managed care rivalry"),
    Edge("INCY", "REGN", "competitor", 0.2, "Biotech sector overlap"),
    Edge("EXAS", "ABT", "competitor", 0.15, "Diagnostics overlap"),

    # ---- Consumer Staples (expansion) ----
    Edge("DG", "DLTR", "competitor", 0.55, "Discount retail rivalry"),
    Edge("DG", "WMT", "competitor", 0.25, "Discount retail overlap"),
    Edge("KR", "WMT", "competitor", 0.35, "Grocery retail rivalry"),
    Edge("KR", "COST", "competitor", 0.2, "Grocery retail overlap"),
    Edge("SYY", "KR", "customer", 0.15, "Food distribution to grocery/restaurants"),
    Edge("SYY", "MCD", "customer", 0.15, "Food distribution to restaurants"),
    Edge("HSY", "MDLZ", "competitor", 0.45, "Confectionery rivalry"),
    Edge("KDP", "PEP", "competitor", 0.35, "Beverage rivalry"),
    Edge("KDP", "KO", "competitor", 0.35, "Beverage rivalry"),
    Edge("STZ", "TAP", "competitor", 0.4, "Beer/alcohol rivalry"),
    Edge("TAP", "MNST", "competitor", 0.15, "Beverage sector overlap"),
    Edge("CHD", "CL", "competitor", 0.35, "Household/personal care rivalry"),
    Edge("CHD", "KMB", "competitor", 0.3, "Household products rivalry"),
    Edge("EL", "CL", "competitor", 0.25, "Personal care/beauty overlap"),
    Edge("CAG", "GIS", "competitor", 0.4, "Packaged foods rivalry"),
    Edge("K", "GIS", "competitor", 0.45, "Packaged foods rivalry"),
    Edge("K", "CAG", "competitor", 0.3, "Packaged foods rivalry"),
    Edge("TSN", "HRL", "competitor", 0.4, "Meat processing rivalry"),
    Edge("TSN", "ADM", "customer", 0.2, "Grain/feed supply relationship"),
    Edge("HRL", "KHC", "competitor", 0.2, "Packaged foods overlap"),

    # ---- Industrials (expansion) ----
    Edge("PCAR", "CMI", "supplier", 0.3, "Engine supplier for heavy trucks"),
    Edge("PCAR", "DE", "competitor", 0.15, "Heavy equipment sector overlap"),
    Edge("CMI", "CAT", "competitor", 0.25, "Engines/power systems overlap"),
    Edge("PH", "ETN", "competitor", 0.4, "Industrial components rivalry"),
    Edge("ETN", "EMR", "competitor", 0.35, "Electrical equipment rivalry"),
    Edge("ROK", "EMR", "competitor", 0.4, "Industrial automation rivalry"),
    Edge("ROK", "HON", "competitor", 0.25, "Industrial automation overlap"),
    Edge("DOV", "ITW", "competitor", 0.3, "Diversified industrials overlap"),
    Edge("IR", "DOV", "competitor", 0.25, "Industrial machinery overlap"),
    Edge("XYL", "AWK", "customer", 0.2, "Water infrastructure equipment supplier"),
    Edge("AME", "ITW", "competitor", 0.2, "Electronic instruments overlap"),
    Edge("FAST", "GWW", "competitor", 0.55, "Industrial distribution rivalry"),
    Edge("WM", "RSG", "competitor", 0.55, "Waste management rivalry"),
    Edge("CTAS", "PAYX", "competitor", 0.15, "Business services overlap"),
    Edge("PAYX", "ADP", "competitor", 0.55, "Payroll/HR services rivalry"),
    Edge("LHX", "RTX", "competitor", 0.35, "Defense electronics rivalry"),
    Edge("LHX", "GD", "competitor", 0.3, "Defense contractor overlap"),
    Edge("TDG", "GE", "competitor", 0.2, "Aerospace components overlap"),
    Edge("TDG", "BA", "customer", 0.25, "Aerospace components supplier"),
    Edge("HII", "GD", "competitor", 0.35, "Shipbuilding/defense rivalry"),
    Edge("LDOS", "NOC", "competitor", 0.25, "Defense/IT services overlap"),
    Edge("AXON", "GD", "competitor", 0.1, "Defense/public-safety tech overlap"),

    # ---- Technology (expansion: semis, networking, cybersecurity, clean-energy tech) ----
    Edge("NXPI", "TXN", "competitor", 0.4, "Analog/automotive semiconductor rivalry"),
    Edge("NXPI", "QCOM", "competitor", 0.3, "Semiconductor overlap"),
    Edge("MCHP", "TXN", "competitor", 0.35, "Analog semiconductor rivalry"),
    Edge("MCHP", "ADI", "competitor", 0.4, "Analog semiconductor rivalry"),
    Edge("MPWR", "ADI", "competitor", 0.35, "Power semiconductor rivalry"),
    Edge("GFS", "TSM", "competitor", 0.3, "Semiconductor foundry rivalry"),
    Edge("GFS", "INTC", "competitor", 0.2, "Semiconductor foundry overlap"),
    Edge("ANET", "CSCO", "competitor", 0.5, "Networking hardware rivalry"),
    Edge("JNPR", "CSCO", "competitor", 0.4, "Networking hardware rivalry"),
    Edge("ANET", "JNPR", "competitor", 0.35, "Networking hardware overlap"),
    Edge("FFIV", "PANW", "competitor", 0.2, "Network security overlap"),
    Edge("AKAM", "NET", "competitor", 0.4, "CDN/edge network rivalry"),
    Edge("AKAM", "CRWD", "partner", 0.1, "Security/CDN ecosystem overlap"),
    Edge("GEN", "CHKP", "competitor", 0.15, "Cybersecurity sector overlap"),
    Edge("CHKP", "PANW", "competitor", 0.4, "Cybersecurity rivalry"),
    Edge("S", "CRWD", "competitor", 0.5, "Endpoint security rivalry"),
    Edge("S", "PANW", "competitor", 0.3, "Cybersecurity rivalry"),
    Edge("CYBR", "OKTA", "competitor", 0.35, "Identity/access security rivalry"),
    Edge("CYBR", "CRWD", "competitor", 0.2, "Cybersecurity overlap"),
    Edge("ENPH", "SEDG", "competitor", 0.55, "Solar inverter rivalry"),
    Edge("ENPH", "FSLR", "partner", 0.15, "Solar industry supply chain overlap"),
    Edge("ROKU", "NFLX", "competitor", 0.2, "Streaming platform overlap"),
    Edge("ROKU", "DIS", "partner", 0.15, "Streaming app distribution"),

    # ---- Energy (expansion) ----
    Edge("PLUG", "FSLR", "competitor", 0.1, "Alternative energy sector overlap"),

    # ---- Materials (expansion) ----
    Edge("MOS", "CF", "competitor", 0.45, "Fertilizer/agri-inputs rivalry"),
    Edge("MOS", "ADM", "customer", 0.2, "Agricultural inputs to agribusiness"),
    Edge("CF", "CTVA", "competitor", 0.15, "Agricultural inputs overlap"),

    # ---- Communication Services (expansion) ----
    Edge("CHTR", "CMCSA", "competitor", 0.55, "Cable broadband rivalry"),
    Edge("CHTR", "T", "competitor", 0.25, "Broadband/wireless overlap"),
    Edge("LUMN", "T", "competitor", 0.2, "Telecom infrastructure overlap"),
    Edge("LUMN", "VZ", "competitor", 0.2, "Telecom infrastructure overlap"),
    Edge("WMG", "SPOT", "partner", 0.35, "Music licensing partnership"),
    Edge("WMG", "LYV", "partner", 0.2, "Music/live entertainment ecosystem"),

    # ---- Technology (expansion) ----
    Edge("CDW", "IBM", "competitor", 0.2, "IT distribution/services overlap"),
    Edge("CDW", "CACI", "competitor", 0.15, "Government/enterprise IT services overlap"),
    Edge("ANSS", "SNPS", "competitor", 0.4, "Engineering simulation software overlap"),
    Edge("ANSS", "CDNS", "competitor", 0.35, "Simulation/chip-design software overlap"),
    Edge("PTC", "ADSK", "competitor", 0.4, "Industrial design/PLM software rivalry"),
    Edge("PTC", "ANSS", "partner", 0.15, "Simulation-PLM integration partnership"),
    Edge("VEEV", "ORCL", "competitor", 0.2, "Enterprise cloud software overlap"),
    Edge("HUBS", "CRM", "competitor", 0.4, "Marketing/CRM software rivalry"),
    Edge("HUBS", "INTU", "competitor", 0.2, "SMB software overlap"),
    Edge("ZM", "TEAM", "competitor", 0.3, "Workplace collaboration rivalry"),
    Edge("ZM", "MSFT", "competitor", 0.4, "Video conferencing rivalry (Teams)"),
    Edge("DBX", "BOX", "competitor", 0.6, "Cloud storage rivalry"),
    Edge("DBX", "MSFT", "competitor", 0.3, "Cloud storage rivalry (OneDrive)"),
    Edge("BOX", "MSFT", "competitor", 0.25, "Cloud content management rivalry"),
    Edge("PATH", "MSFT", "competitor", 0.2, "Automation software overlap (Power Automate)"),
    Edge("U", "RBLX", "competitor", 0.3, "Game development/platform overlap"),
    Edge("U", "EA", "partner", 0.15, "Game engine licensing"),
    Edge("APP", "TTD", "competitor", 0.35, "Ad tech rivalry"),
    Edge("APP", "META", "competitor", 0.25, "Mobile advertising overlap"),
    Edge("ESTC", "SNOW", "competitor", 0.3, "Data/search platform overlap"),
    Edge("ESTC", "DDOG", "competitor", 0.3, "Observability software rivalry"),
    Edge("NTNX", "DELL", "partner", 0.2, "Hybrid cloud infrastructure integration"),
    Edge("NTNX", "HPE", "competitor", 0.25, "Hyperconverged infrastructure rivalry"),
    Edge("WDC", "STX", "competitor", 0.7, "Hard drive/storage rivalry"),
    Edge("WDC", "MU", "competitor", 0.3, "Memory/storage semiconductor overlap"),
    Edge("STX", "MU", "competitor", 0.25, "Storage/memory overlap"),
    Edge("WDC", "DELL", "supplier", 0.35, "Storage drives for servers/PCs"),
    Edge("STX", "DELL", "supplier", 0.3, "Storage drives for servers"),
    Edge("VRT", "NVDA", "partner", 0.4, "Data-center power/cooling infrastructure for AI servers"),
    Edge("VRT", "SMCI", "partner", 0.25, "Data-center infrastructure ecosystem"),
    Edge("VRT", "DELL", "competitor", 0.15, "Data-center infrastructure overlap"),
    Edge("WOLF", "ON", "competitor", 0.4, "Silicon carbide power semiconductor rivalry"),
    Edge("WOLF", "TSLA", "supplier", 0.2, "Silicon carbide chips for EV power electronics"),
    Edge("LSCC", "MCHP", "competitor", 0.3, "Programmable logic/analog semiconductor overlap"),
    Edge("LSCC", "AMD", "competitor", 0.2, "FPGA market overlap (Xilinx now AMD)"),
    Edge("CIEN", "CSCO", "competitor", 0.35, "Optical networking rivalry"),
    Edge("CIEN", "ANET", "competitor", 0.25, "Networking hardware overlap"),
    Edge("CACI", "LDOS", "competitor", 0.4, "Government IT/defense services rivalry"),
    Edge("CACI", "GD", "competitor", 0.2, "Government services overlap"),
    Edge("GLW", "AAPL", "supplier", 0.5, "Gorilla Glass for iPhone displays"),
    Edge("GLW", "TSM", "supplier", 0.2, "Optical fiber/specialty materials for semiconductor supply chain"),

    # ---- Consumer Discretionary (expansion) ----
    Edge("YETI", "GRMN", "competitor", 0.1, "Outdoor/consumer products overlap"),
    Edge("CROX", "DECK", "competitor", 0.5, "Footwear rivalry"),
    Edge("CROX", "NKE", "competitor", 0.2, "Footwear market overlap"),
    Edge("DECK", "NKE", "competitor", 0.3, "Footwear rivalry"),
    Edge("DECK", "LULU", "competitor", 0.15, "Athletic/lifestyle apparel overlap"),
    Edge("ULTA", "EL", "customer", 0.3, "Beauty retail distribution channel"),
    Edge("ULTA", "TGT", "competitor", 0.15, "Beauty retail overlap"),
    Edge("BBY", "AMZN", "competitor", 0.5, "Electronics retail vs e-commerce rivalry"),
    Edge("BBY", "WMT", "competitor", 0.3, "Electronics retail overlap"),
    Edge("AZO", "ORLY", "competitor", 0.7, "Auto parts retail rivalry"),
    Edge("AZO", "TSCO", "competitor", 0.15, "Retail overlap"),
    Edge("TSCO", "HD", "competitor", 0.15, "Home/rural retail overlap"),
    Edge("DRI", "YUM", "competitor", 0.3, "Restaurant rivalry"),
    Edge("DRI", "CMG", "competitor", 0.2, "Restaurant sector overlap"),
    Edge("WEN", "MCD", "competitor", 0.4, "QSR rivalry"),
    Edge("WEN", "DPZ", "competitor", 0.2, "QSR overlap"),
    Edge("POOL", "HD", "customer", 0.15, "Pool supplies distribution through retail"),
    Edge("GRMN", "AAPL", "competitor", 0.25, "Wearables market overlap (Apple Watch)"),

    # ---- Communication Services: advertising ----
    Edge("IPG", "OMC", "competitor", 0.7, "Advertising holding company rivalry"),
    Edge("IPG", "GOOGL", "customer", 0.2, "Digital ad-buying relationship"),
    Edge("OMC", "META", "customer", 0.2, "Digital ad-buying relationship"),

    # ---- Consumer Staples (expansion) ----
    Edge("PM", "MO", "competitor", 0.6, "Tobacco market rivalry (spun apart in 2008)"),
    Edge("KVUE", "JNJ", "partner", 0.4, "Spun off from Johnson & Johnson's consumer health unit"),
    Edge("KVUE", "PG", "competitor", 0.3, "Consumer health/personal care rivalry"),
    Edge("KVUE", "CL", "competitor", 0.2, "Personal care overlap"),

    # ---- Industrials (expansion) ----
    Edge("CARR", "JCI", "competitor", 0.5, "HVAC/building systems rivalry"),
    Edge("CARR", "RTX", "partner", 0.3, "Spun off from Raytheon Technologies (formerly United Technologies)"),
    Edge("OTIS", "RTX", "partner", 0.3, "Spun off from Raytheon Technologies (formerly United Technologies)"),
    Edge("OTIS", "CARR", "partner", 0.2, "Common corporate lineage (both ex-United Technologies)"),
    Edge("JCI", "HON", "competitor", 0.3, "Building automation rivalry"),
    Edge("FTV", "DHR", "competitor", 0.3, "Diversified industrial technology overlap (both ex-Danaher lineage)"),
    Edge("FTV", "AME", "competitor", 0.25, "Industrial instruments overlap"),
    Edge("ROP", "DHR", "competitor", 0.2, "Diversified technology/software overlap"),
    Edge("ROP", "PTC", "competitor", 0.2, "Industrial software overlap"),
    Edge("IEX", "DOV", "competitor", 0.3, "Diversified industrial equipment overlap"),
    Edge("IEX", "XYL", "competitor", 0.25, "Fluidics/water technology overlap"),
    Edge("MAS", "SHW", "competitor", 0.2, "Building products/coatings overlap"),
    Edge("MAS", "DHI", "supplier", 0.3, "Building products for new-home construction"),
    Edge("MAS", "LEN", "supplier", 0.25, "Building products for new-home construction"),
    Edge("BLDR", "DHI", "supplier", 0.35, "Building materials for homebuilders"),
    Edge("BLDR", "LEN", "supplier", 0.3, "Building materials for homebuilders"),
    Edge("BLDR", "PHM", "supplier", 0.3, "Building materials for homebuilders"),
    Edge("JBHT", "ODFL", "competitor", 0.5, "Trucking/freight rivalry"),
    Edge("JBHT", "FDX", "competitor", 0.3, "Freight/logistics overlap"),
    Edge("CHRW", "EXPD", "competitor", 0.55, "Freight brokerage/logistics rivalry"),
    Edge("CHRW", "JBHT", "competitor", 0.3, "Logistics overlap"),
    Edge("EXPD", "FDX", "competitor", 0.2, "Logistics overlap"),
    Edge("ALK", "DAL", "competitor", 0.35, "US airline rivalry"),
    Edge("ALK", "UAL", "competitor", 0.35, "US airline rivalry"),
    Edge("JBLU", "LUV", "competitor", 0.4, "Low-cost airline rivalry"),
    Edge("JBLU", "DAL", "competitor", 0.3, "US airline rivalry"),
    Edge("TXT", "GD", "competitor", 0.3, "Aerospace/defense overlap"),
    Edge("TXT", "BA", "competitor", 0.2, "Aerospace manufacturing overlap"),
    Edge("SNA", "FAST", "competitor", 0.2, "Industrial tools distribution overlap"),
    Edge("SNA", "GWW", "competitor", 0.15, "Industrial distribution overlap"),

    # ---- Materials (expansion) ----
    Edge("VMC", "MLM", "competitor", 0.7, "Construction aggregates rivalry"),
    Edge("VMC", "DHI", "supplier", 0.2, "Aggregates for residential construction"),
    Edge("MLM", "LEN", "supplier", 0.2, "Aggregates for residential construction"),
    Edge("PPG", "SHW", "competitor", 0.6, "Paints & coatings rivalry"),
    Edge("ECL", "DOW", "competitor", 0.2, "Specialty chemicals overlap"),
    Edge("ECL", "SHW", "competitor", 0.15, "Chemicals/coatings sector overlap"),
    Edge("ALLE", "MAS", "competitor", 0.3, "Building/security products overlap"),
    Edge("ALLE", "JCI", "competitor", 0.25, "Building security systems overlap"),

    # ---- Financials (expansion) ----
    Edge("AJG", "MMC", "competitor", 0.5, "Insurance brokerage rivalry"),
    Edge("AJG", "AON", "competitor", 0.45, "Insurance brokerage rivalry"),
    Edge("AJG", "WTW", "competitor", 0.4, "Insurance brokerage rivalry"),
    Edge("ERIE", "PGR", "competitor", 0.3, "Personal insurance rivalry"),
    Edge("ERIE", "ALL", "competitor", 0.3, "P&C insurance overlap"),
    Edge("L", "TRV", "competitor", 0.25, "P&C insurance overlap"),
    Edge("L", "AIG", "competitor", 0.2, "Diversified insurance overlap"),
    Edge("RJF", "SCHW", "competitor", 0.3, "Brokerage/wealth management rivalry"),
    Edge("RJF", "MS", "competitor", 0.25, "Wealth management overlap"),
    Edge("IVZ", "TROW", "competitor", 0.4, "Asset management rivalry"),
    Edge("IVZ", "BEN", "competitor", 0.4, "Asset management rivalry"),
    Edge("IVZ", "BLK", "competitor", 0.3, "Asset management overlap"),
    Edge("MKTX", "ICE", "competitor", 0.3, "Electronic trading platform overlap"),
    Edge("MKTX", "CBOE", "competitor", 0.25, "Trading platform overlap"),

    # ---- Healthcare (expansion) ----
    Edge("RMD", "DXCM", "competitor", 0.15, "Connected medical device overlap"),
    Edge("RMD", "MDT", "competitor", 0.2, "Respiratory/medical device overlap"),
    Edge("COO", "ALGN", "competitor", 0.2, "Specialty medical device overlap (vision/dental)"),
    Edge("WST", "BDX", "competitor", 0.3, "Drug delivery/packaging overlap"),
    Edge("MTD", "WAT", "competitor", 0.5, "Lab instruments rivalry"),
    Edge("MTD", "A", "competitor", 0.4, "Analytical instruments rivalry"),
    Edge("WAT", "A", "competitor", 0.45, "Lab instruments rivalry"),
    Edge("WAT", "DHR", "competitor", 0.3, "Life sciences tools overlap"),
    Edge("A", "TMO", "competitor", 0.35, "Life sciences instruments overlap"),
    Edge("BDX", "ABT", "competitor", 0.3, "Medical devices/diagnostics overlap"),
    Edge("BDX", "SYK", "competitor", 0.2, "Medical device overlap"),
    Edge("STE", "BDX", "competitor", 0.2, "Sterilization/medical products overlap"),
    Edge("DGX", "LH", "competitor", 0.7, "Clinical diagnostics rivalry"),
    Edge("DGX", "UNH", "customer", 0.15, "Lab testing/payer relationship"),
    Edge("LH", "UNH", "customer", 0.15, "Lab testing/payer relationship"),
    Edge("CAH", "MCK", "competitor", 0.6, "Pharmaceutical distribution rivalry"),
    Edge("CAH", "COR", "competitor", 0.55, "Pharmaceutical distribution rivalry"),
    Edge("MCK", "COR", "competitor", 0.55, "Pharmaceutical distribution rivalry"),
    Edge("CAH", "CVS", "customer", 0.2, "Drug distribution to pharmacy retail"),
    Edge("MCK", "CVS", "customer", 0.2, "Drug distribution to pharmacy retail"),
    Edge("COR", "JNJ", "customer", 0.15, "Distributes branded pharmaceuticals"),

    # ---- Real Estate (expansion) ----
    Edge("ARE", "EQIX", "competitor", 0.15, "Specialty REIT sector overlap"),
    Edge("SBAC", "AMT", "competitor", 0.55, "Cell tower REIT rivalry"),
    Edge("SBAC", "CCI", "competitor", 0.5, "Cell tower REIT rivalry"),
    Edge("SBAC", "T", "customer", 0.25, "Tower leasing to wireless carriers"),
    Edge("SBAC", "VZ", "customer", 0.25, "Tower leasing to wireless carriers"),
    Edge("REG", "KIM", "competitor", 0.55, "Retail REIT rivalry"),
    Edge("REG", "FRT", "competitor", 0.5, "Retail REIT rivalry"),
    Edge("KIM", "FRT", "competitor", 0.5, "Retail REIT rivalry"),
    Edge("KIM", "SPG", "competitor", 0.3, "Retail REIT overlap"),
    Edge("HST", "MAR", "partner", 0.3, "Hotel property/brand management relationship"),
    Edge("HST", "HLT", "partner", 0.25, "Hotel property/brand management relationship"),
    Edge("MAA", "AVB", "competitor", 0.5, "Residential REIT rivalry"),
    Edge("MAA", "EQR", "competitor", 0.45, "Residential REIT rivalry"),
    Edge("UDR", "AVB", "competitor", 0.5, "Residential REIT rivalry"),
    Edge("UDR", "MAA", "competitor", 0.45, "Residential REIT rivalry"),

    # ---- Energy: midstream (expansion) ----
    Edge("KMI", "WMB", "competitor", 0.6, "Midstream pipeline rivalry"),
    Edge("KMI", "OKE", "competitor", 0.5, "Midstream pipeline rivalry"),
    Edge("WMB", "OKE", "competitor", 0.5, "Midstream pipeline rivalry"),
    Edge("ET", "KMI", "competitor", 0.5, "Midstream pipeline rivalry"),
    Edge("ET", "WMB", "competitor", 0.5, "Midstream pipeline rivalry"),
    Edge("TRGP", "OKE", "competitor", 0.45, "Midstream/NGL processing rivalry"),
    Edge("KMI", "XOM", "customer", 0.2, "Pipeline transport for oil & gas producers"),
    Edge("WMB", "COP", "customer", 0.2, "Pipeline transport for oil & gas producers"),
    Edge("ET", "EOG", "customer", 0.2, "Pipeline transport for shale producers"),

    # ---- Utilities (expansion) ----
    Edge("PPL", "FE", "competitor", 0.3, "Mid-Atlantic electric utility rivalry"),
    Edge("PPL", "AEP", "competitor", 0.25, "Electric utility overlap"),
    Edge("FE", "AEP", "competitor", 0.3, "Electric utility overlap"),
    Edge("ES", "ED", "competitor", 0.3, "Northeast electric utility rivalry"),
    Edge("ES", "D", "competitor", 0.2, "Northeast utility overlap"),
    Edge("ATO", "SRE", "competitor", 0.25, "Natural gas utility overlap"),
    Edge("CMS", "AEE", "competitor", 0.3, "Midwest utility rivalry"),
    Edge("CMS", "WEC", "competitor", 0.3, "Midwest utility rivalry"),
    Edge("CNP", "SRE", "competitor", 0.2, "Gas/electric multi-utility overlap"),
    Edge("NI", "CMS", "competitor", 0.25, "Midwest gas/electric utility overlap"),
    Edge("LNT", "XEL", "competitor", 0.3, "Midwest electric utility rivalry"),
    Edge("LNT", "WEC", "competitor", 0.25, "Midwest utility overlap"),

    # ---- International e-commerce / internet ----
    Edge("MELI", "AMZN", "competitor", 0.4, "Latin America e-commerce rivalry"),
    Edge("MELI", "SE", "competitor", 0.2, "Emerging-market e-commerce overlap"),
    Edge("SE", "PDD", "competitor", 0.2, "SE Asia/cross-border e-commerce overlap"),
    Edge("CPNG", "AMZN", "competitor", 0.35, "Korea e-commerce vs global rivalry"),
    Edge("BIDU", "GOOGL", "competitor", 0.35, "Search engine rivalry"),
    Edge("PDD", "BABA", "competitor", 0.55, "China e-commerce rivalry"),
    Edge("PDD", "JD", "competitor", 0.5, "China e-commerce rivalry"),
    Edge("JD", "BABA", "competitor", 0.55, "China e-commerce rivalry"),
    Edge("BABA", "AMZN", "competitor", 0.35, "Global e-commerce/cloud rivalry"),
    Edge("JD", "AMZN", "competitor", 0.25, "E-commerce logistics model overlap"),
]

# Sanity: keep only edges whose endpoints exist in the universe.
EDGES = [e for e in EDGES if e.src in COMPANY_BY_TICKER and e.dst in COMPANY_BY_TICKER]


def neighbors(ticker: str) -> list[Edge]:
    """All edges touching `ticker`, either direction."""
    return [e for e in EDGES if e.src == ticker or e.dst == ticker]


def adjacency() -> dict[str, list[tuple[str, Edge]]]:
    """ticker -> [(other_ticker, edge), ...] for graph algorithms."""
    adj: dict[str, list[tuple[str, Edge]]] = {t: [] for t in TICKERS}
    for e in EDGES:
        adj[e.src].append((e.dst, e))
        adj[e.dst].append((e.src, e))
    return adj
